# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bqf = {
    pname = "bqf";
    version = "ebb6d2689e4427452180f17c53f29f7e460236f1";
    src = fetchFromGitHub {
      owner = "kevinhwang91";
      repo = "nvim-bqf";
      rev = "ebb6d2689e4427452180f17c53f29f7e460236f1";
      fetchSubmodules = false;
      sha256 = "sha256-JhVi208hCsenyYy5XIyjeyeAopgw8cHzBm1w2QH+tf4=";
    };
    date = "2025-01-04";
  };
  bufferline = {
    pname = "bufferline";
    version = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
      fetchSubmodules = false;
      sha256 = "sha256-ae4MB6+6v3awvfSUWlau9ASJ147ZpwuX1fvJdfMwo1Q=";
    };
    date = "2025-01-14";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "f67b886d65a029f12ffa298701fb8f1efd89295d";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "f67b886d65a029f12ffa298701fb8f1efd89295d";
      fetchSubmodules = false;
      sha256 = "sha256-lwQLmqm01FihJdad4QRMK23MTrouyOokyuX/3enWjzs=";
    };
    as = "catppuccin";
    date = "2024-12-27";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "886ee73b6d464b2b3e3e6a7ff55ce87feac423a9";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "886ee73b6d464b2b3e3e6a7ff55ce87feac423a9";
      fetchSubmodules = false;
      sha256 = "sha256-c2UE0dLBtoYMvMxg+jXzfsD+wN9sZLvftJq4gGmooZU=";
    };
    date = "2024-12-22";
  };
  crates = {
    pname = "crates";
    version = "bd35b13e94a292ee6e32c351e05ca2202dc9f070";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "bd35b13e94a292ee6e32c351e05ca2202dc9f070";
      fetchSubmodules = false;
      sha256 = "sha256-dj7VXlMbS4HvSc+/WMQprtqWzrYrWaCnSEE0ygp/LcI=";
    };
    date = "2025-01-03";
  };
  direnv = {
    pname = "direnv";
    version = "3e38d855c764bb1bec230130ed0e026fca54e4c8";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "3e38d855c764bb1bec230130ed0e026fca54e4c8";
      fetchSubmodules = false;
      sha256 = "sha256-nWdAIchqGsWiF0cQ7NwePRa1fpugE8duZKqdBaisrAc=";
    };
    date = "2024-07-08";
  };
  evergarden = {
    pname = "evergarden";
    version = "31f39772562b1c03a970f057cd5cbb8cff1e68fc";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "evergarden";
      rev = "31f39772562b1c03a970f057cd5cbb8cff1e68fc";
      fetchSubmodules = false;
      sha256 = "sha256-4JfdunwFNpWkCnCIG6kZRybBqNbPTJrlPvk/RQgJedM=";
    };
    date = "2025-01-14";
  };
  fidget = {
    pname = "fidget";
    version = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
      fetchSubmodules = false;
      sha256 = "sha256-8Gl2Ck4YJGReSEq1Xeh1dpdRq4eImmrxvIHrfxdem3Q=";
    };
    date = "2023-11-09";
  };
  freeze = {
    pname = "freeze";
    version = "65c6e693a1d8ebd816bd3076350efa8e080c1c4a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "65c6e693a1d8ebd816bd3076350efa8e080c1c4a";
      fetchSubmodules = false;
      sha256 = "sha256-m8lsdVTbesC4IlohFFgkVeW3StqIfztfJ3/KAUgLzrI=";
    };
    date = "2024-12-28";
  };
  fzf-lua = {
    pname = "fzf-lua";
    version = "c23f777b28da6aa5603cde1b713e9f6973805d5d";
    src = fetchFromGitHub {
      owner = "ibhagwan";
      repo = "fzf-lua";
      rev = "c23f777b28da6aa5603cde1b713e9f6973805d5d";
      fetchSubmodules = false;
      sha256 = "sha256-SDeWwpx+9sAoN45dS0XWXEGAt8pfmYRiNvFAG5RSm0U=";
    };
    date = "2025-01-21";
  };
  go-nvim = {
    pname = "go-nvim";
    version = "6e5a74b866aa4a112ed85a1169befff2ef82c027";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "go.nvim";
      rev = "6e5a74b866aa4a112ed85a1169befff2ef82c027";
      fetchSubmodules = false;
      sha256 = "sha256-n5aMZ5cPFrPc37tmCXrbHtxwN/vJg5uxZhAx454UwYM=";
    };
    date = "2025-01-16";
  };
  guihua-lua = {
    pname = "guihua-lua";
    version = "d783191eaa75215beae0c80319fcce5e6b3beeda";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "guihua.lua";
      rev = "d783191eaa75215beae0c80319fcce5e6b3beeda";
      fetchSubmodules = false;
      sha256 = "sha256-XpUsbj1boDfbyE8C6SdOvZdkd97682VVC81fvQ5WA/4=";
    };
    date = "2024-11-02";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "5ff183655ad98b5fc50c55c66540375bbd62438c";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "5ff183655ad98b5fc50c55c66540375bbd62438c";
      fetchSubmodules = false;
      sha256 = "sha256-Q4v4E8Iay6rXvtUsM5ULo1cnBYduzTw42kIgJlodq5U=";
    };
    date = "2024-11-26";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "e10626f7fcd51ccd56d7ffc00883ba7e0aa28f78";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "e10626f7fcd51ccd56d7ffc00883ba7e0aa28f78";
      fetchSubmodules = false;
      sha256 = "sha256-0+boInVEzS2myYil/l+frs8PAa/2eJcVTyXnEk6TGvI=";
    };
    date = "2025-01-20";
  };
  keymaps-nvim = {
    pname = "keymaps-nvim";
    version = "62f10ae89dfcf065035c20ad3cda2c84f36e43ab";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "keymaps.nvim";
      rev = "62f10ae89dfcf065035c20ad3cda2c84f36e43ab";
      fetchSubmodules = false;
      sha256 = "sha256-Wgh9uVmKtKOCwo+Z3IFTp6Bv0m4QIju3FVPlxsHRWBg=";
    };
    date = "2024-03-12";
  };
  lazydev = {
    pname = "lazydev";
    version = "8620f82ee3f59ff2187647167b6b47387a13a018";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "8620f82ee3f59ff2187647167b6b47387a13a018";
      fetchSubmodules = false;
      sha256 = "sha256-ZaAkGTwEBoOjy6RyIPKFLJswxfOu886bN899UakXAv0=";
    };
    date = "2024-12-20";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lspkind = {
    pname = "lspkind";
    version = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
      fetchSubmodules = false;
      sha256 = "sha256-OCvKUBGuzwy8OWOL1x3Z3fo+0+GyBMI9TX41xSveqvE=";
    };
    date = "2024-12-05";
  };
  lualine = {
    pname = "lualine";
    version = "2a5bae925481f999263d6f5ed8361baef8df4f83";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "2a5bae925481f999263d6f5ed8361baef8df4f83";
      fetchSubmodules = false;
      sha256 = "sha256-IN6Qz3jGxUcylYiRTyd8j6me3pAoqJsJXtFUvph/6EI=";
    };
    date = "2024-11-08";
  };
  luasnip = {
    pname = "luasnip";
    version = "c9b9a22904c97d0eb69ccb9bab76037838326817";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "c9b9a22904c97d0eb69ccb9bab76037838326817";
      fetchSubmodules = false;
      sha256 = "sha256-3ecm5SDTcSOh256xSQPHhddQfMpepiEIpv58fHXrVg0=";
    };
    as = "luasnip";
    date = "2025-01-04";
  };
  lz-n = {
    pname = "lz-n";
    version = "cd2ef2cd178517170f0246567ee6368b1cadf50b";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "cd2ef2cd178517170f0246567ee6368b1cadf50b";
      fetchSubmodules = false;
      sha256 = "sha256-J8/UMygdIdSdlOEJ6SuicqAXsYdo4Pn2Di5bgtsqKGU=";
    };
    start = "true";
    date = "2025-01-19";
  };
  markview = {
    pname = "markview";
    version = "6e9f1840ba33e5318285ad97c22676f55b753479";
    src = fetchFromGitHub {
      owner = "OXY2DEV";
      repo = "markview.nvim";
      rev = "6e9f1840ba33e5318285ad97c22676f55b753479";
      fetchSubmodules = false;
      sha256 = "sha256-ZbZWF7hcJysfnbMraqsmK7PFSEU70P7TBKpZqgriTmk=";
    };
    date = "2025-01-08";
  };
  mini-ai = {
    pname = "mini-ai";
    version = "ebb04799794a7f94628153991e6334c3304961b8";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.ai";
      rev = "ebb04799794a7f94628153991e6334c3304961b8";
      fetchSubmodules = false;
      sha256 = "sha256-b/776l9nYM9e2atzXrvOk9dCxjzIuW/+iINC/yPv88Y=";
    };
    date = "2024-12-08";
  };
  mini-align = {
    pname = "mini-align";
    version = "e715137aece7d05734403d793b8b6b64486bc812";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.align";
      rev = "e715137aece7d05734403d793b8b6b64486bc812";
      fetchSubmodules = false;
      sha256 = "sha256-oHub8dEihIx4kcP3CD9GXG1SUObJUVpH4bg2Z6PmadQ=";
    };
    date = "2024-12-30";
  };
  mini-bracketed = {
    pname = "mini-bracketed";
    version = "0091e11fabe34973fc038a8d0d0485202742e403";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.bracketed";
      rev = "0091e11fabe34973fc038a8d0d0485202742e403";
      fetchSubmodules = false;
      sha256 = "sha256-y+tGFF1H37ES/hnEtr3GJK3GeB6D5s8ZdSpvzl+lh3s=";
    };
    date = "2025-01-16";
  };
  mini-diff = {
    pname = "mini-diff";
    version = "00f072250061ef498f91ed226918c9ec31a416a4";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.diff";
      rev = "00f072250061ef498f91ed226918c9ec31a416a4";
      fetchSubmodules = false;
      sha256 = "sha256-dRvW/1lfVShiHmRU0mQA5g5xDyQ0EVtVLLZ0y6WSedg=";
    };
    date = "2024-12-27";
  };
  mini-files = {
    pname = "mini-files";
    version = "43fe43c78e94fca04c04ace3ed1b4530975cafed";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.files";
      rev = "43fe43c78e94fca04c04ace3ed1b4530975cafed";
      fetchSubmodules = false;
      sha256 = "sha256-jVVwRBVHyX+jA1rSznBa8D934mEZX+HFaYKc6V6VNDs=";
    };
    date = "2025-01-21";
  };
  mini-git = {
    pname = "mini-git";
    version = "fc13dde6cfe87cf25a4fd1ee177c0d157468436b";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini-git";
      rev = "fc13dde6cfe87cf25a4fd1ee177c0d157468436b";
      fetchSubmodules = false;
      sha256 = "sha256-rXuKopyZBCBbpKuytCdm8keruSNK1ohk2NdeZv1wifI=";
    };
    date = "2025-01-10";
  };
  mini-move = {
    pname = "mini-move";
    version = "4caa1c212f5ca3d1633d21cfb184808090ed74b1";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.move";
      rev = "4caa1c212f5ca3d1633d21cfb184808090ed74b1";
      fetchSubmodules = false;
      sha256 = "sha256-nX0eAlhMnKhAftgM6qeHUuawagumLQMPKDkqZNPLljg=";
    };
    date = "2024-08-15";
  };
  mini-pairs = {
    pname = "mini-pairs";
    version = "7e834c5937d95364cc1740e20d673afe2d034cdb";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.pairs";
      rev = "7e834c5937d95364cc1740e20d673afe2d034cdb";
      fetchSubmodules = false;
      sha256 = "sha256-PtHxLKU1smVTx655r5SINxuz5CJmZWnBW70T8zJ/oxM=";
    };
    date = "2024-10-11";
  };
  mini-splitjoin = {
    pname = "mini-splitjoin";
    version = "3e92f6764e770ba392325cad3a4497adcada695f";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.splitjoin";
      rev = "3e92f6764e770ba392325cad3a4497adcada695f";
      fetchSubmodules = false;
      sha256 = "sha256-LDIbh5KfupTI4zkYOlLmVCd3DuZRhx5lTASN53VG34g=";
    };
    date = "2024-07-01";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "aa5e245829dd12d8ff0c96ef11da28681d6049aa";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "aa5e245829dd12d8ff0c96ef11da28681d6049aa";
      fetchSubmodules = false;
      sha256 = "sha256-okWJlG0KOdg1ShvkIIMnPSoOzGd7K84eDcp5kx6eVP8=";
    };
    date = "2024-12-08";
  };
  mini-trailspace = {
    pname = "mini-trailspace";
    version = "3a328e62559c33014e422fb9ae97afc4208208b1";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.trailspace";
      rev = "3a328e62559c33014e422fb9ae97afc4208208b1";
      fetchSubmodules = false;
      sha256 = "sha256-JKYvFz8g8kVZvxE44RhwoHXQykghXx7ebW/Mj1ZdJIw=";
    };
    date = "2024-09-06";
  };
  neogen = {
    pname = "neogen";
    version = "dd0301bfba1f83a3bc009b5430fce7aa3cee6941";
    src = fetchFromGitHub {
      owner = "danymat";
      repo = "neogen";
      rev = "dd0301bfba1f83a3bc009b5430fce7aa3cee6941";
      fetchSubmodules = false;
      sha256 = "sha256-EzAbn9oDnzgi5ajNulzFz2thGoSlpr/if3xSpY57BG4=";
    };
    date = "2024-12-27";
  };
  none-ls = {
    pname = "none-ls";
    version = "ed8f80849ef1ad31c2f74679fafdef7801091247";
    src = fetchFromGitHub {
      owner = "nvimtools";
      repo = "none-ls.nvim";
      rev = "ed8f80849ef1ad31c2f74679fafdef7801091247";
      fetchSubmodules = false;
      sha256 = "sha256-AE+M4utQEz+/ZNyOn+QiDF1LiCt2YP9yQMPw3dQ0rJQ=";
    };
    date = "2025-01-21";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "ed12b5379ff203d0a15f01d71a64848b591e4adc";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "ed12b5379ff203d0a15f01d71a64848b591e4adc";
      fetchSubmodules = false;
      sha256 = "sha256-g5ND+k4fxBmyq+74pFRQFKp5/kLBQJkI3YfUSIeSb0M=";
    };
    date = "2025-01-19";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "d1871c84b218931cc758dbbde1fec8e90c6d465c";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "d1871c84b218931cc758dbbde1fec8e90c6d465c";
      fetchSubmodules = false;
      sha256 = "sha256-W8AXSCntb8v5zkxaBcGFbahLJ88/c4z7wV0JoSKKsGc=";
    };
    date = "2025-01-21";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "8649f694d3e76ee10c19255dece6411c29206a54";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "8649f694d3e76ee10c19255dece6411c29206a54";
      fetchSubmodules = false;
      sha256 = "sha256-0p5n/V8Jlj9XyxV/fuMwsbQ7oV5m9H2GqZZEA/njxCQ=";
    };
    date = "2023-11-30";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "22f29093eae7785773ee9d543f8750348b1a195c";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "22f29093eae7785773ee9d543f8750348b1a195c";
      fetchSubmodules = false;
      sha256 = "sha256-6vNfc7E9DMXF0IBXJCLA8Rp+uOgbDch/Q7beW0ys3Vo=";
    };
    date = "2025-01-20";
  };
  nvim-tree = {
    pname = "nvim-tree";
    version = "fca0b67c0b5a31727fb33addc4d9c100736a2894";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "fca0b67c0b5a31727fb33addc4d9c100736a2894";
      fetchSubmodules = false;
      sha256 = "sha256-b8YOOIYML9aKy4Y7S+iLKIaTfCqrxK1wB/ZaeFRCUmo=";
    };
    date = "2025-01-18";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "07bd1b53bf465e42d53253b48b7437892d6c45e8";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "07bd1b53bf465e42d53253b48b7437892d6c45e8";
      fetchSubmodules = false;
      sha256 = "sha256-RjSPnxlIAW8k4ed4PphxX/ogWsDFabPDuulAnAh9L/U=";
    };
    date = "2025-01-21";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "aafa5c187a15701a7299a392b907ec15d9a7075f";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "aafa5c187a15701a7299a392b907ec15d9a7075f";
      fetchSubmodules = false;
      sha256 = "sha256-lUlEVEzXX8iCPxXIlpwkqBc19hks8qTvz4FdDNsTviI=";
    };
    date = "2025-01-10";
  };
  plenary = {
    pname = "plenary";
    version = "3707cdb1e43f5cea73afb6037e6494e7ce847a66";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "3707cdb1e43f5cea73afb6037e6494e7ce847a66";
      fetchSubmodules = false;
      sha256 = "sha256-18zX3kZ42ynRefFP0mOcy6ESEpejTukjNi4jCRXx48A=";
    };
    start = "true";
    date = "2025-01-12";
  };
  py_lsp = {
    pname = "py_lsp";
    version = "d738992fb8eb0bf23c72e53bf9d50e380654f83e";
    src = fetchFromGitHub {
      owner = "hallerpatrick";
      repo = "py_lsp.nvim";
      rev = "d738992fb8eb0bf23c72e53bf9d50e380654f83e";
      fetchSubmodules = false;
      sha256 = "sha256-oaDeYISCo5pMj9qFHw4W3PhQxWn+cl/8ttq7oA72OW8=";
    };
    date = "2025-01-20";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "08103ea02643a93065fe7dbc4ed22275719fc338";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "08103ea02643a93065fe7dbc4ed22275719fc338";
      fetchSubmodules = false;
      sha256 = "sha256-SDMoqQwY3cKj5c5wHFdE+G0ZWVIeLjF6DU67tfDfi8w=";
    };
    date = "2024-12-10";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "85b80abaa09cbbc039e3095b2f515b3cf8cadd11";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "85b80abaa09cbbc039e3095b2f515b3cf8cadd11";
      fetchSubmodules = false;
      sha256 = "sha256-zWHXYs3XdnoszqOFY3hA2L5mNn1a44OAeKv3lL3EMEw=";
    };
    date = "2025-01-12";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "8cf9705d98cc77837aa388a5d48f9a73f27f4782";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "8cf9705d98cc77837aa388a5d48f9a73f27f4782";
      fetchSubmodules = false;
      sha256 = "sha256-SSBv1+GxuVpYhpCH//6EXFJ4NXZdZM0pGe19f53JpiA=";
    };
    date = "2025-01-19";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "5be212138af55d3dcae9d77b5b14f63634243e3d";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "5be212138af55d3dcae9d77b5b14f63634243e3d";
      fetchSubmodules = false;
      sha256 = "sha256-jtZ6cta98Wx4vZHcXq0jKfOfpQtTFRFrH5W+/8jyL5g=";
    };
    date = "2025-01-21";
  };
  shelf-nvim = {
    pname = "shelf-nvim";
    version = "c580fbffa2599ab6236486d35102c30598f60812";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "shelf.nvim";
      rev = "c580fbffa2599ab6236486d35102c30598f60812";
      fetchSubmodules = false;
      sha256 = "sha256-phO1/tOZ9Qq3M7no+G9PFPB+Gqf0eHSWnBw15SMEX3w=";
    };
    date = "2024-06-24";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "f7d07bcbc2b79e00088e8b71729b74dd39037280";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "f7d07bcbc2b79e00088e8b71729b74dd39037280";
      fetchSubmodules = false;
      sha256 = "sha256-eamzryTq7uOpNgLoFd9bpswXJH3VdycsEH2r8VSAurU=";
    };
    date = "2025-01-21";
  };
  symbol-usage = {
    pname = "symbol-usage";
    version = "0f9b3da014b7e41559b643e7461fcabb2a7dc83a";
    src = fetchFromGitHub {
      owner = "Wansmer";
      repo = "symbol-usage.nvim";
      rev = "0f9b3da014b7e41559b643e7461fcabb2a7dc83a";
      fetchSubmodules = false;
      sha256 = "sha256-vNVrh8MV7KZoh2MtP+hAr6Uz20qMMMUcbua/W71lRn0=";
    };
    date = "2024-09-13";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
      fetchSubmodules = false;
      sha256 = "sha256-at9OSBtQqyiDdxKdNn2x6z4k8xrDD90sACKEK7uKNUM=";
    };
    date = "2025-01-14";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "e76134e682c1a866e3dfcdaeb691eb7b01068668";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "e76134e682c1a866e3dfcdaeb691eb7b01068668";
      fetchSubmodules = false;
      sha256 = "sha256-4Y1TXxnrMLqwFlmbj39JTlcUToP80kWU+FpPUrYdz8s=";
    };
    date = "2024-12-30";
  };
  treewalker = {
    pname = "treewalker";
    version = "9a29abe2141d930321a88c3a1ff9d914f4fd3257";
    src = fetchFromGitHub {
      owner = "aaronik";
      repo = "treewalker.nvim";
      rev = "9a29abe2141d930321a88c3a1ff9d914f4fd3257";
      fetchSubmodules = false;
      sha256 = "sha256-pd9Yfz5oqmQZimxkCyrl6dAEh3TyDdcj/mfO1KGH4iQ=";
    };
    date = "2025-01-18";
  };
  trouble = {
    pname = "trouble";
    version = "50481f414bd3c1a40122c1d759d7e424d5fafe84";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "50481f414bd3c1a40122c1d759d7e424d5fafe84";
      fetchSubmodules = false;
      sha256 = "sha256-Z2STeDZ8uhfyfH1TqSbRdWPYdPMxOb9s8/hLS76Fm5E=";
    };
    date = "2025-01-15";
  };
  typescript-tools = {
    pname = "typescript-tools";
    version = "35e397ce467bedbbbb5bfcd0aa79727b59a08d4a";
    src = fetchFromGitHub {
      owner = "pmizio";
      repo = "typescript-tools.nvim";
      rev = "35e397ce467bedbbbb5bfcd0aa79727b59a08d4a";
      fetchSubmodules = false;
      sha256 = "sha256-x32NzZYFK6yovlvE3W8NevYA0UT0qvwKle1irFwmuvM=";
    };
    date = "2024-12-04";
  };
  undotree = {
    pname = "undotree";
    version = "2556c6800b210b2096b55b66e74b4cc1d9ebbe4f";
    src = fetchFromGitHub {
      owner = "mbbill";
      repo = "undotree";
      rev = "2556c6800b210b2096b55b66e74b4cc1d9ebbe4f";
      fetchSubmodules = false;
      sha256 = "sha256-0DnRarEuDPdYo+zkwH47jG4B4fGjvL1LxqEoFQ7vpjE=";
    };
    date = "2025-01-01";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "d74a7cff4cfcf84f83cc7eccfa365488f3bbabc2";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "d74a7cff4cfcf84f83cc7eccfa365488f3bbabc2";
      fetchSubmodules = false;
      sha256 = "sha256-dsIuUz5o9Q44vrXz3U50d4inASoug8pR7zGXkBL5+t8=";
    };
    date = "2025-01-20";
  };
  wakatime = {
    pname = "wakatime";
    version = "3cb40867cb5a3120f9bef76eff88edc7f1dc1a23";
    src = fetchFromGitHub {
      owner = "wakatime";
      repo = "vim-wakatime";
      rev = "3cb40867cb5a3120f9bef76eff88edc7f1dc1a23";
      fetchSubmodules = false;
      sha256 = "sha256-HxLmX+qws8A6+mFBGMdru2E3NXJ91P0HtDKMX8ryMzI=";
    };
    date = "2024-04-29";
  };
  which-key = {
    pname = "which-key";
    version = "1f8d414f61e0b05958c342df9b6a4c89ce268766";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "1f8d414f61e0b05958c342df9b6a4c89ce268766";
      fetchSubmodules = false;
      sha256 = "sha256-9V74V01dCqg1w5fpzzCmyfhR3/AYQg2MCIYkkjFv1go=";
    };
    date = "2025-01-05";
  };
  zk-nvim = {
    pname = "zk-nvim";
    version = "10089c398df925b8db51fd659501d2cb044003b9";
    src = fetchFromGitHub {
      owner = "mickael-menu";
      repo = "zk-nvim";
      rev = "10089c398df925b8db51fd659501d2cb044003b9";
      fetchSubmodules = false;
      sha256 = "sha256-i9UOny7vq3O+g0TnL1wwTGnw18g79CyZvOM0kGptt64=";
    };
    date = "2025-01-04";
  };
}
