# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alpha = {
    pname = "alpha";
    version = "de72250e054e5e691b9736ee30db72c65d560771";
    src = fetchFromGitHub {
      owner = "goolord";
      repo = "alpha-nvim";
      rev = "de72250e054e5e691b9736ee30db72c65d560771";
      fetchSubmodules = false;
      sha256 = "sha256-sNi5qarejYqM4/J7lBZI3gjVLxer5FBPq8K6qjqcMjA=";
    };
    date = "2024-11-14";
  };
  bqf = {
    pname = "bqf";
    version = "68d3c20f6bee49105dcfde3df1f7ec972529f2a3";
    src = fetchFromGitHub {
      owner = "kevinhwang91";
      repo = "nvim-bqf";
      rev = "68d3c20f6bee49105dcfde3df1f7ec972529f2a3";
      fetchSubmodules = false;
      sha256 = "sha256-kfK3jGy5kHoL1iiEgHDBqRGFDdliZohgAuJM2qbgylk=";
    };
    date = "2024-12-20";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "5d9582dbbe37e465f7f93ca6e3dd60cd20eea44f";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "5d9582dbbe37e465f7f93ca6e3dd60cd20eea44f";
      fetchSubmodules = false;
      sha256 = "sha256-B8/BkGf1xNHOzFaBsxoYTx8CGlxVvLBOKVlNZm1iZEA=";
    };
    as = "catppuccin";
    date = "2024-12-24";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "886ee73b6d464b2b3e3e6a7ff55ce87feac423a9";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "886ee73b6d464b2b3e3e6a7ff55ce87feac423a9";
      fetchSubmodules = false;
      sha256 = "sha256-c2UE0dLBtoYMvMxg+jXzfsD+wN9sZLvftJq4gGmooZU=";
    };
    date = "2024-12-22";
  };
  crates = {
    pname = "crates";
    version = "8bf8358ee326d5d8c11dcd7ac0bcc9ff97dbc785";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "8bf8358ee326d5d8c11dcd7ac0bcc9ff97dbc785";
      fetchSubmodules = false;
      sha256 = "sha256-DIG0MXRTit4iEVoLlgsTK4znjam/QDjeZEpIDn6KHiE=";
    };
    date = "2024-09-26";
  };
  direnv = {
    pname = "direnv";
    version = "3e38d855c764bb1bec230130ed0e026fca54e4c8";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "3e38d855c764bb1bec230130ed0e026fca54e4c8";
      fetchSubmodules = false;
      sha256 = "sha256-nWdAIchqGsWiF0cQ7NwePRa1fpugE8duZKqdBaisrAc=";
    };
    date = "2024-07-08";
  };
  evergarden = {
    pname = "evergarden";
    version = "3cd3437ad80883300ee57aeba6116229fb988972";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "evergarden";
      rev = "3cd3437ad80883300ee57aeba6116229fb988972";
      fetchSubmodules = false;
      sha256 = "sha256-rsZmTs8Dmhya57j46bGf1ZjLWGhFcK5ajurUJnkCBvA=";
    };
    date = "2024-12-09";
  };
  fidget = {
    pname = "fidget";
    version = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
      fetchSubmodules = false;
      sha256 = "sha256-8Gl2Ck4YJGReSEq1Xeh1dpdRq4eImmrxvIHrfxdem3Q=";
    };
    date = "2023-11-09";
  };
  freeze = {
    pname = "freeze";
    version = "0025c3a01cdd2c26760812ba94b1f95e13520b00";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "0025c3a01cdd2c26760812ba94b1f95e13520b00";
      fetchSubmodules = false;
      sha256 = "sha256-MkvXC3mBbRPisbJFcjGsl2cGVdBnbyiMOJUbcGTzL+0=";
    };
    date = "2024-11-14";
  };
  go-nvim = {
    pname = "go-nvim";
    version = "c6d5ca26377d01c4de1f7bff1cd62c8b43baa6bc";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "go.nvim";
      rev = "c6d5ca26377d01c4de1f7bff1cd62c8b43baa6bc";
      fetchSubmodules = false;
      sha256 = "sha256-rv+4im9kh8VhbDbhoMLaUBD4pYKEfkUUPw/6R9EzqO8=";
    };
    date = "2024-12-01";
  };
  guihua-lua = {
    pname = "guihua-lua";
    version = "d783191eaa75215beae0c80319fcce5e6b3beeda";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "guihua.lua";
      rev = "d783191eaa75215beae0c80319fcce5e6b3beeda";
      fetchSubmodules = false;
      sha256 = "sha256-XpUsbj1boDfbyE8C6SdOvZdkd97682VVC81fvQ5WA/4=";
    };
    date = "2024-11-02";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "5ff183655ad98b5fc50c55c66540375bbd62438c";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "5ff183655ad98b5fc50c55c66540375bbd62438c";
      fetchSubmodules = false;
      sha256 = "sha256-Q4v4E8Iay6rXvtUsM5ULo1cnBYduzTw42kIgJlodq5U=";
    };
    date = "2024-11-26";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "259357fa4097e232730341fa60988087d189193a";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "259357fa4097e232730341fa60988087d189193a";
      fetchSubmodules = false;
      sha256 = "sha256-H3lUQZDvgj3a2STYeMUDiOYPe7rfsy08tJ4SlDd+LuE=";
    };
    date = "2024-12-04";
  };
  keymaps-nvim = {
    pname = "keymaps-nvim";
    version = "62f10ae89dfcf065035c20ad3cda2c84f36e43ab";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "keymaps.nvim";
      rev = "62f10ae89dfcf065035c20ad3cda2c84f36e43ab";
      fetchSubmodules = false;
      sha256 = "sha256-Wgh9uVmKtKOCwo+Z3IFTp6Bv0m4QIju3FVPlxsHRWBg=";
    };
    date = "2024-03-12";
  };
  lazydev = {
    pname = "lazydev";
    version = "8620f82ee3f59ff2187647167b6b47387a13a018";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "8620f82ee3f59ff2187647167b6b47387a13a018";
      fetchSubmodules = false;
      sha256 = "sha256-ZaAkGTwEBoOjy6RyIPKFLJswxfOu886bN899UakXAv0=";
    };
    date = "2024-12-20";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lspkind = {
    pname = "lspkind";
    version = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
      fetchSubmodules = false;
      sha256 = "sha256-OCvKUBGuzwy8OWOL1x3Z3fo+0+GyBMI9TX41xSveqvE=";
    };
    date = "2024-12-05";
  };
  ltex-extra = {
    pname = "ltex-extra";
    version = "24acd044ce7a26b3cdb537cbd094de37c3e1ac45";
    src = fetchFromGitHub {
      owner = "barreiroleo";
      repo = "ltex-extra.nvim";
      rev = "24acd044ce7a26b3cdb537cbd094de37c3e1ac45";
      fetchSubmodules = false;
      sha256 = "sha256-OGeeEIF+z03DdJO2d2kzQ0lZnIYLabp6irYPqYgbCbc=";
    };
    date = "2024-06-15";
  };
  lualine = {
    pname = "lualine";
    version = "2a5bae925481f999263d6f5ed8361baef8df4f83";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "2a5bae925481f999263d6f5ed8361baef8df4f83";
      fetchSubmodules = false;
      sha256 = "sha256-IN6Qz3jGxUcylYiRTyd8j6me3pAoqJsJXtFUvph/6EI=";
    };
    date = "2024-11-08";
  };
  luasnip = {
    pname = "luasnip";
    version = "33b06d72d220aa56a7ce80a0dd6f06c70cd82b9d";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "33b06d72d220aa56a7ce80a0dd6f06c70cd82b9d";
      fetchSubmodules = false;
      sha256 = "sha256-efDe3RXncnNVkj37AmIv8oj0DKurB50Dziao5FGTLP4=";
    };
    as = "luasnip";
    date = "2024-12-02";
  };
  lz-n = {
    pname = "lz-n";
    version = "317064a7de9ddc27febc0bb9dc26c4d2a480217e";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "317064a7de9ddc27febc0bb9dc26c4d2a480217e";
      fetchSubmodules = false;
      sha256 = "sha256-RHz8gUKS631umXBVNE4NDtOBuXwjU0MAeCVmPOIZAng=";
    };
    start = "true";
    date = "2024-12-22";
  };
  markview = {
    pname = "markview";
    version = "72cd34279e94ee96ee33bdf30a87b00e6d45319d";
    src = fetchFromGitHub {
      owner = "OXY2DEV";
      repo = "markview.nvim";
      rev = "72cd34279e94ee96ee33bdf30a87b00e6d45319d";
      fetchSubmodules = false;
      sha256 = "sha256-4D4jB9CmamMAdpEodw4MdDyJVU6EMsh8P4gLs7p4E40=";
    };
    date = "2024-11-23";
  };
  mini-ai = {
    pname = "mini-ai";
    version = "ebb04799794a7f94628153991e6334c3304961b8";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.ai";
      rev = "ebb04799794a7f94628153991e6334c3304961b8";
      fetchSubmodules = false;
      sha256 = "sha256-b/776l9nYM9e2atzXrvOk9dCxjzIuW/+iINC/yPv88Y=";
    };
    date = "2024-12-08";
  };
  mini-align = {
    pname = "mini-align";
    version = "acf1ad6031e49553ed887a2a5e3603211346f1de";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.align";
      rev = "acf1ad6031e49553ed887a2a5e3603211346f1de";
      fetchSubmodules = false;
      sha256 = "sha256-ng3OsPMuQHbavRfrWGhi87ONdh7WOKnOAv670EJyYB4=";
    };
    date = "2024-12-08";
  };
  mini-bracketed = {
    pname = "mini-bracketed";
    version = "daf2bff8172bc84bfb934f765275618f5e7844a8";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.bracketed";
      rev = "daf2bff8172bc84bfb934f765275618f5e7844a8";
      fetchSubmodules = false;
      sha256 = "sha256-JrczeJ4LHlIR4fXpzGTolwTX4t/Cx0SVh6XZ0sGSXkY=";
    };
    date = "2024-09-27";
  };
  mini-diff = {
    pname = "mini-diff";
    version = "5947342c95a9c2e24c659b54bb8ef083da4495ad";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.diff";
      rev = "5947342c95a9c2e24c659b54bb8ef083da4495ad";
      fetchSubmodules = false;
      sha256 = "sha256-Mc5nb0cpAi9iKHg3vxPamw2KEKH2q5lsjoS2L4g+K24=";
    };
    date = "2024-12-03";
  };
  mini-files = {
    pname = "mini-files";
    version = "72cc9045c1011f2c158117bd5a0d339792b7f34a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.files";
      rev = "72cc9045c1011f2c158117bd5a0d339792b7f34a";
      fetchSubmodules = false;
      sha256 = "sha256-l/varREPUT91CnJlWcMDl6+6GNeI2AfdvYCWH3EHsFM=";
    };
    date = "2024-12-12";
  };
  mini-git = {
    pname = "mini-git";
    version = "f75ae3855f595e55e1a8a96521ffa01012632b28";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini-git";
      rev = "f75ae3855f595e55e1a8a96521ffa01012632b28";
      fetchSubmodules = false;
      sha256 = "sha256-DwswjGP8L/D2sff+FqdQAfvIXvBFyBRKmdqXv2jy/rQ=";
    };
    date = "2024-09-07";
  };
  mini-move = {
    pname = "mini-move";
    version = "4caa1c212f5ca3d1633d21cfb184808090ed74b1";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.move";
      rev = "4caa1c212f5ca3d1633d21cfb184808090ed74b1";
      fetchSubmodules = false;
      sha256 = "sha256-nX0eAlhMnKhAftgM6qeHUuawagumLQMPKDkqZNPLljg=";
    };
    date = "2024-08-15";
  };
  mini-pairs = {
    pname = "mini-pairs";
    version = "7e834c5937d95364cc1740e20d673afe2d034cdb";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.pairs";
      rev = "7e834c5937d95364cc1740e20d673afe2d034cdb";
      fetchSubmodules = false;
      sha256 = "sha256-PtHxLKU1smVTx655r5SINxuz5CJmZWnBW70T8zJ/oxM=";
    };
    date = "2024-10-11";
  };
  mini-splitjoin = {
    pname = "mini-splitjoin";
    version = "3e92f6764e770ba392325cad3a4497adcada695f";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.splitjoin";
      rev = "3e92f6764e770ba392325cad3a4497adcada695f";
      fetchSubmodules = false;
      sha256 = "sha256-LDIbh5KfupTI4zkYOlLmVCd3DuZRhx5lTASN53VG34g=";
    };
    date = "2024-07-01";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "aa5e245829dd12d8ff0c96ef11da28681d6049aa";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "aa5e245829dd12d8ff0c96ef11da28681d6049aa";
      fetchSubmodules = false;
      sha256 = "sha256-okWJlG0KOdg1ShvkIIMnPSoOzGd7K84eDcp5kx6eVP8=";
    };
    date = "2024-12-08";
  };
  mini-trailspace = {
    pname = "mini-trailspace";
    version = "3a328e62559c33014e422fb9ae97afc4208208b1";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.trailspace";
      rev = "3a328e62559c33014e422fb9ae97afc4208208b1";
      fetchSubmodules = false;
      sha256 = "sha256-JKYvFz8g8kVZvxE44RhwoHXQykghXx7ebW/Mj1ZdJIw=";
    };
    date = "2024-09-06";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "ce43f2eb2a52492157d7742e5f684b9a42bb3e5c";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "ce43f2eb2a52492157d7742e5f684b9a42bb3e5c";
      fetchSubmodules = false;
      sha256 = "sha256-W9jtfVXHC8MQJwdbxakNqhd+xh/auQb3U09XKdN2Wzw=";
    };
    date = "2024-10-09";
  };
  none-ls = {
    pname = "none-ls";
    version = "08744d575f64e6b94c8f9d7db8777d6b9134b28e";
    src = fetchFromGitHub {
      owner = "nvimtools";
      repo = "none-ls.nvim";
      rev = "08744d575f64e6b94c8f9d7db8777d6b9134b28e";
      fetchSubmodules = false;
      sha256 = "sha256-Et01dtH/HvbFliDlxIA00lAG8NgcdFiqRs5BEvliRec=";
    };
    date = "2024-12-25";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "078d5aa3b7a12ee44b45107f16119c085b720316";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "078d5aa3b7a12ee44b45107f16119c085b720316";
      fetchSubmodules = false;
      sha256 = "sha256-jhb7Cv1aSAFHzt3I8TAddK5HIn7FUg07wPH4IXFd/SM=";
    };
    date = "2024-12-24";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "c580f34bc5fdca8aaf737a9ab8a5d775cb940e57";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "c580f34bc5fdca8aaf737a9ab8a5d775cb940e57";
      fetchSubmodules = false;
      sha256 = "sha256-UUW32unKgBZmighFNiEFmBcIPr/bcCdrW+wp3idZr4o=";
    };
    date = "2024-12-23";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "8649f694d3e76ee10c19255dece6411c29206a54";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "8649f694d3e76ee10c19255dece6411c29206a54";
      fetchSubmodules = false;
      sha256 = "sha256-0p5n/V8Jlj9XyxV/fuMwsbQ7oV5m9H2GqZZEA/njxCQ=";
    };
    date = "2023-11-30";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "fbef5d32be8466dd76544a257d3f3dce20082a07";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "fbef5d32be8466dd76544a257d3f3dce20082a07";
      fetchSubmodules = false;
      sha256 = "sha256-Sd7IR5roXHOKRCxhqtYMhWfEltyRJMDEMDO/ecSKenE=";
    };
    date = "2024-09-22";
  };
  nvim-tree = {
    pname = "nvim-tree";
    version = "68fc4c20f5803444277022c681785c5edd11916d";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "68fc4c20f5803444277022c681785c5edd11916d";
      fetchSubmodules = false;
      sha256 = "sha256-4PmP31vYPH9xw4AjV5rDSKvcvZGTnIaPfR4Bwc0lAiA=";
    };
    date = "2024-12-22";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "ac6a72a6f83218216948e898362f09029b8035dc";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "ac6a72a6f83218216948e898362f09029b8035dc";
      fetchSubmodules = false;
      sha256 = "sha256-9UEPTtba6gW+1FR2S+BKPmoD1M4+GzeaH+QBgw9PN1c=";
    };
    date = "2024-12-25";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "c1a86a2c386c55efc02fa2ec2c3a914af653d954";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "c1a86a2c386c55efc02fa2ec2c3a914af653d954";
      fetchSubmodules = false;
      sha256 = "sha256-BexnFXBg+cttJTiwnqlyIzrpN13p9LCVCCzSqbT8uCc=";
    };
    date = "2024-12-24";
  };
  plenary = {
    pname = "plenary";
    version = "2d9b06177a975543726ce5c73fca176cedbffe9d";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "2d9b06177a975543726ce5c73fca176cedbffe9d";
      fetchSubmodules = false;
      sha256 = "sha256-bmmPekAvuBvLQmrnnX0n+FRBqfVxBsObhxIEkDGAla4=";
    };
    start = "true";
    date = "2024-09-17";
  };
  py_lsp = {
    pname = "py_lsp";
    version = "fe28db286c5cd3feb8e415d9f11cdaaf827e6c5a";
    src = fetchFromGitHub {
      owner = "hallerpatrick";
      repo = "py_lsp.nvim";
      rev = "fe28db286c5cd3feb8e415d9f11cdaaf827e6c5a";
      fetchSubmodules = false;
      sha256 = "sha256-4OH1dBDaiz+bK9oc7Z8qXvUcgARul0FoJQ3gQVT4aFM=";
    };
    date = "2024-11-17";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "08103ea02643a93065fe7dbc4ed22275719fc338";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "08103ea02643a93065fe7dbc4ed22275719fc338";
      fetchSubmodules = false;
      sha256 = "sha256-SDMoqQwY3cKj5c5wHFdE+G0ZWVIeLjF6DU67tfDfi8w=";
    };
    date = "2024-12-10";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "77e5bad54227dcfe3878ffbda88ab1efdaacb475";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "77e5bad54227dcfe3878ffbda88ab1efdaacb475";
      fetchSubmodules = false;
      sha256 = "sha256-qDyEf+SflbDEweK5cZP/YZX4yAw0UGSTWgRai5RC8/I=";
    };
    date = "2024-12-15";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "6db1fe9e3f005b2e0921c7302d2c195eeb90a451";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "6db1fe9e3f005b2e0921c7302d2c195eeb90a451";
      fetchSubmodules = false;
      sha256 = "sha256-jUSCVtUGD1qlUVJcli73sdlp3j2LXXqoSyw9dhC4B/8=";
    };
    date = "2024-12-24";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "545d8814f624fb5239c4691fa0914549540e6f53";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "545d8814f624fb5239c4691fa0914549540e6f53";
      fetchSubmodules = false;
      sha256 = "sha256-zLNqNgEUaKmTExk6KVUCMUxagQ6Q811BlHENdgbjRSw=";
    };
    date = "2024-12-23";
  };
  shelf-nvim = {
    pname = "shelf-nvim";
    version = "c580fbffa2599ab6236486d35102c30598f60812";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "shelf.nvim";
      rev = "c580fbffa2599ab6236486d35102c30598f60812";
      fetchSubmodules = false;
      sha256 = "sha256-phO1/tOZ9Qq3M7no+G9PFPB+Gqf0eHSWnBw15SMEX3w=";
    };
    date = "2024-06-24";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "98df370703b3c47a297988f3e55ce99628639590";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "98df370703b3c47a297988f3e55ce99628639590";
      fetchSubmodules = false;
      sha256 = "sha256-Gvd2QfAgrpRxJvZ41LAOPRrDGwVdeZUb8BGrzzcpcHU=";
    };
    date = "2024-12-20";
  };
  telescope = {
    pname = "telescope";
    version = "2eca9ba22002184ac05eddbe47a7fe2d5a384dfc";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "2eca9ba22002184ac05eddbe47a7fe2d5a384dfc";
      fetchSubmodules = false;
      sha256 = "sha256-npb61MZYAotz71Co5G1dUeIqWt7GVeqZNz0A2Yz2dy4=";
    };
    date = "2024-11-29";
  };
  telescope-project = {
    pname = "telescope-project";
    version = "1d7920e799fc5001dffc7bd10909a86e0358eaf4";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-project.nvim";
      rev = "1d7920e799fc5001dffc7bd10909a86e0358eaf4";
      fetchSubmodules = false;
      sha256 = "sha256-qEORRWYKBpK7fn7se8g+5uuVBJNu0T4JHSc0C2QzNDY=";
    };
    date = "2024-12-01";
  };
  telescope-ui-select = {
    pname = "telescope-ui-select";
    version = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-ui-select.nvim";
      rev = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
      fetchSubmodules = false;
      sha256 = "sha256-YRhNmmG4gx9Ht8JwjQfbTjJyTHEuZmtP6lqnhOsk8bE=";
    };
    date = "2023-12-04";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "ae0a2afb47cf7395dc400e5dc4e05274bf4fb9e0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "ae0a2afb47cf7395dc400e5dc4e05274bf4fb9e0";
      fetchSubmodules = false;
      sha256 = "sha256-EH4Sy7qNkzOgA1INFzrtsRfD79TgMqSbKUdundyw22w=";
    };
    date = "2024-09-16";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "87b2d6a3cab8e2bd9a0255427074285f0365398d";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "87b2d6a3cab8e2bd9a0255427074285f0365398d";
      fetchSubmodules = false;
      sha256 = "sha256-g1FwgCc3a8Fak0Nb0gQQ+SI44uyAGaH1tIk1qpaAPEY=";
    };
    date = "2024-11-09";
  };
  trouble = {
    pname = "trouble";
    version = "46cf952fc115f4c2b98d4e208ed1e2dce08c9bf6";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "46cf952fc115f4c2b98d4e208ed1e2dce08c9bf6";
      fetchSubmodules = false;
      sha256 = "sha256-JhnERZfma2JHFEn/DElVmrSU5KxM2asx3SJ+86lCfoo=";
    };
    date = "2024-11-27";
  };
  typescript-tools = {
    pname = "typescript-tools";
    version = "35e397ce467bedbbbb5bfcd0aa79727b59a08d4a";
    src = fetchFromGitHub {
      owner = "pmizio";
      repo = "typescript-tools.nvim";
      rev = "35e397ce467bedbbbb5bfcd0aa79727b59a08d4a";
      fetchSubmodules = false;
      sha256 = "sha256-x32NzZYFK6yovlvE3W8NevYA0UT0qvwKle1irFwmuvM=";
    };
    date = "2024-12-04";
  };
  undotree = {
    pname = "undotree";
    version = "78b5241191852ffa9bb5da5ff2ee033160798c3b";
    src = fetchFromGitHub {
      owner = "mbbill";
      repo = "undotree";
      rev = "78b5241191852ffa9bb5da5ff2ee033160798c3b";
      fetchSubmodules = false;
      sha256 = "sha256-XU2n5S2XLIQcPUJESzW+g/ZAXqJo/9uIHYtFutlqmvA=";
    };
    date = "2024-09-18";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "fcb4db52e7f65b95705aa58f0f2df1312c1f2df2";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "fcb4db52e7f65b95705aa58f0f2df1312c1f2df2";
      fetchSubmodules = false;
      sha256 = "sha256-PJewEivZ1sAn2vBhwxfIHE+rAmY+9GYPNqID5zsey8c=";
    };
    date = "2024-12-15";
  };
  wakatime = {
    pname = "wakatime";
    version = "3cb40867cb5a3120f9bef76eff88edc7f1dc1a23";
    src = fetchFromGitHub {
      owner = "wakatime";
      repo = "vim-wakatime";
      rev = "3cb40867cb5a3120f9bef76eff88edc7f1dc1a23";
      fetchSubmodules = false;
      sha256 = "sha256-HxLmX+qws8A6+mFBGMdru2E3NXJ91P0HtDKMX8ryMzI=";
    };
    date = "2024-04-29";
  };
  which-key = {
    pname = "which-key";
    version = "8ab96b38a2530eacba5be717f52e04601eb59326";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "8ab96b38a2530eacba5be717f52e04601eb59326";
      fetchSubmodules = false;
      sha256 = "sha256-f/+sYMDEguB5ZDiYiQAsDvdF/2cVcWnLBU+9qwigk4s=";
    };
    date = "2024-12-15";
  };
  zk-nvim = {
    pname = "zk-nvim";
    version = "42dc341d897ac4da3d4a9c5c506a36153473f021";
    src = fetchFromGitHub {
      owner = "mickael-menu";
      repo = "zk-nvim";
      rev = "42dc341d897ac4da3d4a9c5c506a36153473f021";
      fetchSubmodules = false;
      sha256 = "sha256-HbqQZYvQunBsiEG1P8Xfl3fCZ0qxfFavWqTBGQhCPPs=";
    };
    date = "2024-11-20";
  };
}
