# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bqf = {
    pname = "bqf";
    version = "e20417d5e589e03eaaaadc4687904528500608be";
    src = fetchFromGitHub {
      owner = "kevinhwang91";
      repo = "nvim-bqf";
      rev = "e20417d5e589e03eaaaadc4687904528500608be";
      fetchSubmodules = false;
      sha256 = "sha256-prYpUlsPIESgA3HXSk5WNFXhxAYVFZeOMQoYZxq9rj8=";
    };
    date = "2025-03-29";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "1bf070129c0b6f77cc23f6a2212dcdc868308c52";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "1bf070129c0b6f77cc23f6a2212dcdc868308c52";
      fetchSubmodules = false;
      sha256 = "sha256-4GpFqo1IDxikmsY6muTJ55+AYPURLMHt7L6lmboyYvI=";
    };
    as = "catppuccin";
    date = "2025-05-04";
  };
  chai-nvim = {
    pname = "chai-nvim";
    version = "5b3142493114ade681dfad63417e5989c11f0f6d";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "chai.nvim";
      rev = "5b3142493114ade681dfad63417e5989c11f0f6d";
      fetchSubmodules = false;
      sha256 = "sha256-T2KHSYdRNbqAPpZrzzRBkTmhS8YV1eiHfnRR1QG5D9k=";
    };
    as = "chai";
    start = "true";
    date = "2025-03-21";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  crates = {
    pname = "crates";
    version = "25f31372ab6f504d4fd7cfee836ad459caed8e68";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "25f31372ab6f504d4fd7cfee836ad459caed8e68";
      fetchSubmodules = false;
      sha256 = "sha256-UEDDXObbUX25AJQXl9itjJ1N2AlYYExvzPenX6rdr28=";
    };
    date = "2025-05-14";
  };
  direnv = {
    pname = "direnv";
    version = "a2f1264909463fd012b7b0b6bbfebc282c5d2834";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "a2f1264909463fd012b7b0b6bbfebc282c5d2834";
      fetchSubmodules = false;
      sha256 = "sha256-nAnZte8okf8V6gH2Egy/32o3W8xznbYhsYBPQ+9F470=";
    };
    date = "2025-04-23";
  };
  evergarden = {
    pname = "evergarden";
    version = "de538e9aac1358872c118e0d7bc45462fc8205c8";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "nvim";
      rev = "de538e9aac1358872c118e0d7bc45462fc8205c8";
      fetchSubmodules = false;
      sha256 = "sha256-CiRiZRmD7tuy/fNQwYJohiS1KSL+7ihTm29cMHunUWE=";
    };
    as = "evergarden";
    date = "2025-04-25";
  };
  fidget = {
    pname = "fidget";
    version = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
      fetchSubmodules = false;
      sha256 = "sha256-8Gl2Ck4YJGReSEq1Xeh1dpdRq4eImmrxvIHrfxdem3Q=";
    };
    date = "2023-11-09";
  };
  freeze = {
    pname = "freeze";
    version = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
      fetchSubmodules = false;
      sha256 = "sha256-VdFmSRBP7Up0j5+rp7ZkfTdQmduJjsl6EZ9gf27vgZg=";
    };
    date = "2025-03-25";
  };
  fzf-lua = {
    pname = "fzf-lua";
    version = "5af306b30f699513669efdf51cf50a6deab53968";
    src = fetchFromGitHub {
      owner = "ibhagwan";
      repo = "fzf-lua";
      rev = "5af306b30f699513669efdf51cf50a6deab53968";
      fetchSubmodules = false;
      sha256 = "sha256-QqUiKI8NqyB34Hs/MR0Y1EVqVrvvS3Lwr7AixlPDVOc=";
    };
    date = "2025-05-13";
  };
  hunk-nvim = {
    pname = "hunk-nvim";
    version = "48713c5348bb0ba001a6ea781f301dcd74fe88d4";
    src = fetchFromGitHub {
      owner = "julienvincent";
      repo = "hunk.nvim";
      rev = "48713c5348bb0ba001a6ea781f301dcd74fe88d4";
      fetchSubmodules = false;
      sha256 = "sha256-Bv3Bc+Fs4zH21bGm8+Ip58uEJws6GilCGq4oP1OP9So=";
    };
    date = "2025-05-14";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "08a02e14c8c0d42fa7a92c30a98fd04d6993b35d";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "08a02e14c8c0d42fa7a92c30a98fd04d6993b35d";
      fetchSubmodules = false;
      sha256 = "sha256-6STviireN52R7engW3c0R2Po8hHSP/apqhXvectH0So=";
    };
    date = "2025-04-01";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
      fetchSubmodules = false;
      sha256 = "sha256-0q/V+b4UrDRnaC/eRWOi9HU9a61vQSAM9/C8ZQyKt+Y=";
    };
    date = "2025-03-18";
  };
  keymaps-nvim = {
    pname = "keymaps-nvim";
    version = "221a1015f5c5f2530379983e1dc200a202f487dd";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "keymaps.nvim";
      rev = "221a1015f5c5f2530379983e1dc200a202f487dd";
      fetchSubmodules = false;
      sha256 = "sha256-afMAPHITrHKxHQKd64goFUncfbKH81t6Xyh5pFCiSTg=";
    };
    date = "2025-03-17";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lualine = {
    pname = "lualine";
    version = "15884cee63a8c205334ab13ab1c891cd4d27101a";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "15884cee63a8c205334ab13ab1c891cd4d27101a";
      fetchSubmodules = false;
      sha256 = "sha256-wfNEDR3uR8Y6hZhzcnuukQ2yMz7rCvuc4li/0rkPRTA=";
    };
    date = "2025-04-22";
  };
  lz-n = {
    pname = "lz-n";
    version = "e85b83c7c2534c7ba2e23a6cecb00a76d2d5fa22";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "e85b83c7c2534c7ba2e23a6cecb00a76d2d5fa22";
      fetchSubmodules = false;
      sha256 = "sha256-gkXQGonZfewMnS05ugmt1GxFicCQtIKPPS1Yi6tGruk=";
    };
    start = "true";
    date = "2025-05-11";
  };
  markit-nvim = {
    pname = "markit-nvim";
    version = "9b031afab214aa6e6467f275f55640989f438925";
    src = fetchFromGitHub {
      owner = "2KAbhishek";
      repo = "markit.nvim";
      rev = "9b031afab214aa6e6467f275f55640989f438925";
      fetchSubmodules = false;
      sha256 = "sha256-LCvACs8hHxquwBcCthfrdWQAQd8jrOwhsuZAkjqCZSQ=";
    };
    date = "2025-02-23";
  };
  markview = {
    pname = "markview";
    version = "b35c51593573ee3de145838c04477be34e6db3a2";
    src = fetchFromGitHub {
      owner = "OXY2DEV";
      repo = "markview.nvim";
      rev = "b35c51593573ee3de145838c04477be34e6db3a2";
      fetchSubmodules = false;
      sha256 = "sha256-P48GW042004zVcaqWKC9QTURIeOrVBe4Ie/deHGzl6M=";
    };
    date = "2025-05-14";
  };
  mini-ai = {
    pname = "mini-ai";
    version = "e139eb1101beb0250fea322f8c07a42f0f175688";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.ai";
      rev = "e139eb1101beb0250fea322f8c07a42f0f175688";
      fetchSubmodules = false;
      sha256 = "sha256-rN7nchgckFy0ZUrGAnEaLzK9fAPJkyqacM2SSju3h9E=";
    };
    date = "2025-04-01";
  };
  mini-align = {
    pname = "mini-align";
    version = "2b42ac0be7d570c2208f9e334ecef13453cd222d";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.align";
      rev = "2b42ac0be7d570c2208f9e334ecef13453cd222d";
      fetchSubmodules = false;
      sha256 = "sha256-idf1EhUm60c2jPwK6hSwP1RKw06jHFDsI/ZP4tKWaIo=";
    };
    date = "2025-04-01";
  };
  mini-bracketed = {
    pname = "mini-bracketed";
    version = "079b8375e40ebf3f8af319ad835263ff390c3965";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.bracketed";
      rev = "079b8375e40ebf3f8af319ad835263ff390c3965";
      fetchSubmodules = false;
      sha256 = "sha256-lii1QK3wsPd2+nuV+xDAlRBOYs3qOponbXIBQBD587Q=";
    };
    date = "2025-05-08";
  };
  mini-diff = {
    pname = "mini-diff";
    version = "ec8a5ae365c5d15920721ea42b1351dbc9e61f2d";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.diff";
      rev = "ec8a5ae365c5d15920721ea42b1351dbc9e61f2d";
      fetchSubmodules = false;
      sha256 = "sha256-5FnfQGz/HiVTwWPfWZqWpHkB2sjCemjPtDP6ulGhZb0=";
    };
    date = "2025-05-06";
  };
  mini-files = {
    pname = "mini-files";
    version = "49c855977e9f4821d1ed8179ed44fe098b93ea2a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.files";
      rev = "49c855977e9f4821d1ed8179ed44fe098b93ea2a";
      fetchSubmodules = false;
      sha256 = "sha256-UDt1RUp9J80IlrYAUupCVbKAo8Wma1hImP+AlFY/Aog=";
    };
    date = "2025-05-05";
  };
  mini-git = {
    pname = "mini-git";
    version = "a0ddc6302f654523053c28109e8b6dbbf05c08f8";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini-git";
      rev = "a0ddc6302f654523053c28109e8b6dbbf05c08f8";
      fetchSubmodules = false;
      sha256 = "sha256-wlu1LzBwyB12inqGP+Vp2Wbf2Dyy00fVVcF5EI72wG0=";
    };
    date = "2025-04-06";
  };
  mini-icons = {
    pname = "mini-icons";
    version = "397ed3807e96b59709ef3292f0a3e253d5c1dc0a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.icons";
      rev = "397ed3807e96b59709ef3292f0a3e253d5c1dc0a";
      fetchSubmodules = false;
      sha256 = "sha256-/sdLtMOOGeVvFDBB9N4CyUHpGXtUi1ZJ9dIpvxZ9C4Q=";
    };
    date = "2025-04-01";
  };
  mini-move = {
    pname = "mini-move";
    version = "4fe4a855fee53c66b0f3255a4b54ddc2ae6b308c";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.move";
      rev = "4fe4a855fee53c66b0f3255a4b54ddc2ae6b308c";
      fetchSubmodules = false;
      sha256 = "sha256-92y5p9g03GMfyQsO0qVUp6exIXypkpq+lJSUH7pNojU=";
    };
    date = "2025-04-01";
  };
  mini-operators = {
    pname = "mini-operators";
    version = "2df4df029be367adfc781a8a1b5e8067d2d979df";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.operators";
      rev = "2df4df029be367adfc781a8a1b5e8067d2d979df";
      fetchSubmodules = false;
      sha256 = "sha256-eVS9rWZVKZ/pwNuk0Xi3WhDEVVI79EbnOVsY5liqMjY=";
    };
    date = "2025-05-03";
  };
  mini-pairs = {
    pname = "mini-pairs";
    version = "69864a2efb36c030877421634487fd90db1e4298";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.pairs";
      rev = "69864a2efb36c030877421634487fd90db1e4298";
      fetchSubmodules = false;
      sha256 = "sha256-ORD4ERYhN2F/MRpDlJvuH2wq8pgMsw/NMWiNX2eUcis=";
    };
    date = "2025-04-01";
  };
  mini-splitjoin = {
    pname = "mini-splitjoin";
    version = "70240d5d3881ff1b2b1d7902450f98a6fa303800";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.splitjoin";
      rev = "70240d5d3881ff1b2b1d7902450f98a6fa303800";
      fetchSubmodules = false;
      sha256 = "sha256-Cx/yXpFnTpleLkN4PevtzYYyiyTAv2qBRQhtRjS45Oo=";
    };
    date = "2025-04-01";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "5aab42fcdcf31fa010f012771eda5631c077840a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "5aab42fcdcf31fa010f012771eda5631c077840a";
      fetchSubmodules = false;
      sha256 = "sha256-fsJf1wOLPLSjAgGcjrckwrK1qkpyPjKHMeqEj589XkM=";
    };
    date = "2025-04-01";
  };
  mini-trailspace = {
    pname = "mini-trailspace";
    version = "39a0460c025a605519fdd6bea1ce870642429996";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.trailspace";
      rev = "39a0460c025a605519fdd6bea1ce870642429996";
      fetchSubmodules = false;
      sha256 = "sha256-z3kevj896GtxGd44cIM0sU84sBkV2fQf2gq6UzvbJbU=";
    };
    date = "2025-04-01";
  };
  mossy-nvim = {
    pname = "mossy-nvim";
    version = "c53caee82da149b5355cf5f3189d2f341649d8e0";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "mossy.nvim";
      rev = "c53caee82da149b5355cf5f3189d2f341649d8e0";
      fetchSubmodules = false;
      sha256 = "sha256-mD6nj0x+JWr6Mn0mGR4M5U0sIVV/swgMBFU5RK1oIBg=";
    };
    date = "2025-05-14";
  };
  neogen = {
    pname = "neogen";
    version = "d7f9461727751fb07f82011051338a9aba07581d";
    src = fetchFromGitHub {
      owner = "danymat";
      repo = "neogen";
      rev = "d7f9461727751fb07f82011051338a9aba07581d";
      fetchSubmodules = false;
      sha256 = "sha256-uXV8YZLO44lFys1RfIqsvonC2YEYwb1iiaiLfsON3hE=";
    };
    date = "2025-05-03";
  };
  nui = {
    pname = "nui";
    version = "f535005e6ad1016383f24e39559833759453564e";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "f535005e6ad1016383f24e39559833759453564e";
      fetchSubmodules = false;
      sha256 = "sha256-SJc9nfV6cnBKYwRWsv0iHy+RbET8frNV85reICf+pt8=";
    };
    date = "2025-05-03";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "517df88cf2afb36652830df2c655df2da416a0ae";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "517df88cf2afb36652830df2c655df2da416a0ae";
      fetchSubmodules = false;
      sha256 = "sha256-yOPUgqHe0WT437aX8kp0P/reNgjZUNNRG7hvDgaeXT0=";
    };
    date = "2025-03-01";
  };
  nvim-lint = {
    pname = "nvim-lint";
    version = "fdb04e9285edefbe25a02a31a35e8fbb10fe054d";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-lint";
      rev = "fdb04e9285edefbe25a02a31a35e8fbb10fe054d";
      fetchSubmodules = false;
      sha256 = "sha256-qVsi8+g2eC/PqzfWpWGSwxndaoIuApQfONyApMTJUUY=";
    };
    date = "2025-05-13";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "5a137448fd921a0c5d3939cb75e60d21f64e4606";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "5a137448fd921a0c5d3939cb75e60d21f64e4606";
      fetchSubmodules = false;
      sha256 = "sha256-ewksNjdNoSg1w/UXA3HpG4HkmeAounqDY7KqvY6IDAI=";
    };
    start = "true";
    date = "2025-05-14";
  };
  nvim-nio = {
    pname = "nvim-nio";
    version = "21f5324bfac14e22ba26553caf69ec76ae8a7662";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "nvim-nio";
      rev = "21f5324bfac14e22ba26553caf69ec76ae8a7662";
      fetchSubmodules = false;
      sha256 = "sha256-eDbzJAGdUBhTwuD0Nt9FihZj1MmVdQfn/GKIybuu5a8=";
    };
    date = "2025-01-20";
  };
  nvim-tree = {
    pname = "nvim-tree";
    version = "e7d1b7dadc62fe2eccc17d814354b0a5688621ce";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "e7d1b7dadc62fe2eccc17d814354b0a5688621ce";
      fetchSubmodules = false;
      sha256 = "sha256-shDHnAoHGsITh7kFySXnzm+GGn3D2qS59eC95SkMJsc=";
    };
    date = "2025-05-09";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "066fd6505377e3fd4aa219e61ce94c2b8bdb0b79";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "066fd6505377e3fd4aa219e61ce94c2b8bdb0b79";
      fetchSubmodules = false;
      sha256 = "sha256-bYbwIVii2mxFyro91ogCVLkIyrMNP4QJRSGNVcZPVEU=";
    };
    date = "2025-05-12";
  };
  plenary = {
    pname = "plenary";
    version = "857c5ac632080dba10aae49dba902ce3abf91b35";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "857c5ac632080dba10aae49dba902ce3abf91b35";
      fetchSubmodules = false;
      sha256 = "sha256-8FV5RjF7QbDmQOQynpK7uRKONKbPRYbOPugf9ZxNvUs=";
    };
    start = "true";
    date = "2025-02-11";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "08103ea02643a93065fe7dbc4ed22275719fc338";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "08103ea02643a93065fe7dbc4ed22275719fc338";
      fetchSubmodules = false;
      sha256 = "sha256-SDMoqQwY3cKj5c5wHFdE+G0ZWVIeLjF6DU67tfDfi8w=";
    };
    date = "2024-12-10";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "55ad4fb76ab68460f700599b7449385f0c4e858e";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "55ad4fb76ab68460f700599b7449385f0c4e858e";
      fetchSubmodules = false;
      sha256 = "sha256-EeJvGtBwZgR7i9PEnGe4NTRiDQCgVKkSh5t8Xy5EYfE=";
    };
    date = "2025-04-16";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "cb532f57c1ed2463c66df683468eb3994e554002";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "cb532f57c1ed2463c66df683468eb3994e554002";
      fetchSubmodules = false;
      sha256 = "sha256-t3FJHIMP4QkyyG7MGFB0SKp7LXmTOUMLAREt5XeQMgI=";
    };
    date = "2025-05-11";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "df87d16fc4ea7c2c67cfc00b513861738693fe07";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "df87d16fc4ea7c2c67cfc00b513861738693fe07";
      fetchSubmodules = false;
      sha256 = "sha256-CKEyNBSPpqn60MLAVaDvde28bEZNvr1hOUJsW73H68Y=";
    };
    date = "2025-05-10";
  };
  shelf-nvim = {
    pname = "shelf-nvim";
    version = "6de47a367bc39eb058dd030be5b45c731314701d";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "shelf.nvim";
      rev = "6de47a367bc39eb058dd030be5b45c731314701d";
      fetchSubmodules = false;
      sha256 = "sha256-XNohRWnDq0Iu8Qn37o7hUVLyFLfwHXCyo/cNBuC0wg8=";
    };
    date = "2025-05-09";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "bc0630e43be5699bb94dadc302c0d21615421d93";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      fetchSubmodules = false;
      sha256 = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
    date = "2025-03-01";
  };
  symbol-usage = {
    pname = "symbol-usage";
    version = "e07c07dfe7504295a369281e95a24e1afa14b243";
    src = fetchFromGitHub {
      owner = "Wansmer";
      repo = "symbol-usage.nvim";
      rev = "e07c07dfe7504295a369281e95a24e1afa14b243";
      fetchSubmodules = false;
      sha256 = "sha256-zWT6ZGYGpWLwuUrMlmyTIE5UZtPLX2FnywhycTxUaRQ=";
    };
    date = "2025-05-03";
  };
  tabby-nvim = {
    pname = "tabby-nvim";
    version = "0207f9eba073be14688ffdbec68064835066e770";
    src = fetchFromGitHub {
      owner = "nanozuki";
      repo = "tabby.nvim";
      rev = "0207f9eba073be14688ffdbec68064835066e770";
      fetchSubmodules = false;
      sha256 = "sha256-I6ShLFhRj3pdSFqEOViXhWzL9UnrXcs7IFtgRsnIo30=";
    };
    date = "2025-05-03";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
      fetchSubmodules = false;
      sha256 = "sha256-at9OSBtQqyiDdxKdNn2x6z4k8xrDD90sACKEK7uKNUM=";
    };
    date = "2025-01-14";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "9a88eae817ef395952e08650b3283726786fb5fb";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "9a88eae817ef395952e08650b3283726786fb5fb";
      fetchSubmodules = false;
      sha256 = "sha256-fytbX+L12TK45YKFU9K+iFJcDrwboKabihc2LtX29J4=";
    };
    date = "2025-03-09";
  };
  treewalker = {
    pname = "treewalker";
    version = "c8aaeeaa64bac4afb60d0c253bbcbd765e6529d1";
    src = fetchFromGitHub {
      owner = "aaronik";
      repo = "treewalker.nvim";
      rev = "c8aaeeaa64bac4afb60d0c253bbcbd765e6529d1";
      fetchSubmodules = false;
      sha256 = "sha256-DtZqU0Imhqdic3UYtqHA5uF+SPMR5DlwPJ9n8TAsjI8=";
    };
    date = "2025-05-12";
  };
  trouble = {
    pname = "trouble";
    version = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
      fetchSubmodules = false;
      sha256 = "sha256-au9wp88a0CutEf2f8Bi0vFTUR0zvQKgFX1vMVg4myGI=";
    };
    date = "2025-02-12";
  };
  undotree = {
    pname = "undotree";
    version = "b951b87b46c34356d44aa71886aecf9dd7f5788a";
    src = fetchFromGitHub {
      owner = "mbbill";
      repo = "undotree";
      rev = "b951b87b46c34356d44aa71886aecf9dd7f5788a";
      fetchSubmodules = false;
      sha256 = "sha256-HGf4Toe+12YZtIalvANDXAtksCsnxQkZbcevOAnl5G4=";
    };
    date = "2025-03-13";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "4a745ea72fa93bb15dd077109afbb3d1809383f2";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "4a745ea72fa93bb15dd077109afbb3d1809383f2";
      fetchSubmodules = false;
      sha256 = "sha256-1AteNwnc7lCHLIwM8Ejm2T9VTIDM+CeAfvAUeSQRFKE=";
    };
    date = "2025-02-19";
  };
  wakatime = {
    pname = "wakatime";
    version = "3cb40867cb5a3120f9bef76eff88edc7f1dc1a23";
    src = fetchFromGitHub {
      owner = "wakatime";
      repo = "vim-wakatime";
      rev = "3cb40867cb5a3120f9bef76eff88edc7f1dc1a23";
      fetchSubmodules = false;
      sha256 = "sha256-HxLmX+qws8A6+mFBGMdru2E3NXJ91P0HtDKMX8ryMzI=";
    };
    date = "2024-04-29";
  };
  yosu-nvim = {
    pname = "yosu-nvim";
    version = "b92a8d9e294025f1d249a24f0b2538c9a8a14007";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "yosu.nvim";
      rev = "b92a8d9e294025f1d249a24f0b2538c9a8a14007";
      fetchSubmodules = false;
      sha256 = "sha256-ao7fnihe/aKyL3XAgqgIj5aVUhVS20JsYV56+QfNoJ4=";
    };
    date = "2025-05-09";
  };
  zk-nvim = {
    pname = "zk-nvim";
    version = "69e6f9c9793d4884a15310314f33dc4f0d57275a";
    src = fetchFromGitHub {
      owner = "mickael-menu";
      repo = "zk-nvim";
      rev = "69e6f9c9793d4884a15310314f33dc4f0d57275a";
      fetchSubmodules = false;
      sha256 = "sha256-lues/HfnLLHLXRmif82FHXtDpP4YA/wI2ehjKAJpPm8=";
    };
    date = "2025-05-09";
  };
}
