# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bqf = {
    pname = "bqf";
    version = "e20417d5e589e03eaaaadc4687904528500608be";
    src = fetchFromGitHub {
      owner = "kevinhwang91";
      repo = "nvim-bqf";
      rev = "e20417d5e589e03eaaaadc4687904528500608be";
      fetchSubmodules = false;
      sha256 = "sha256-prYpUlsPIESgA3HXSk5WNFXhxAYVFZeOMQoYZxq9rj8=";
    };
    date = "2025-03-29";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "b7bbdf93b42866f166af98d39a2563eedb7cabac";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "b7bbdf93b42866f166af98d39a2563eedb7cabac";
      fetchSubmodules = false;
      sha256 = "sha256-YLM54Cpz7CRsnmJqAtlu+hWNyVUQ8DD+gnES9OJlHDk=";
    };
    as = "catppuccin";
    date = "2025-05-01";
  };
  chai-nvim = {
    pname = "chai-nvim";
    version = "5b3142493114ade681dfad63417e5989c11f0f6d";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "chai.nvim";
      rev = "5b3142493114ade681dfad63417e5989c11f0f6d";
      fetchSubmodules = false;
      sha256 = "sha256-T2KHSYdRNbqAPpZrzzRBkTmhS8YV1eiHfnRR1QG5D9k=";
    };
    start = "true";
    as = "chai";
    date = "2025-03-21";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "a5c390f8d8e85b501b22dcb2f30e0cbbd69d5ff0";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "a5c390f8d8e85b501b22dcb2f30e0cbbd69d5ff0";
      fetchSubmodules = false;
      sha256 = "sha256-8zXdRLugrLRK+sg9k9I1MSE5KAdnY017IkquCQisZt4=";
    };
    date = "2025-04-25";
  };
  crates = {
    pname = "crates";
    version = "2c8f4fab02e3e9ea42c6ad9b547e4207a914a397";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "2c8f4fab02e3e9ea42c6ad9b547e4207a914a397";
      fetchSubmodules = false;
      sha256 = "sha256-Oh3krtXo38wwrcc9YWLS0uw3q7tuw8eU/QG+sUmqtDU=";
    };
    date = "2025-04-29";
  };
  direnv = {
    pname = "direnv";
    version = "a2f1264909463fd012b7b0b6bbfebc282c5d2834";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "a2f1264909463fd012b7b0b6bbfebc282c5d2834";
      fetchSubmodules = false;
      sha256 = "sha256-nAnZte8okf8V6gH2Egy/32o3W8xznbYhsYBPQ+9F470=";
    };
    date = "2025-04-23";
  };
  evergarden = {
    pname = "evergarden";
    version = "de538e9aac1358872c118e0d7bc45462fc8205c8";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "nvim";
      rev = "de538e9aac1358872c118e0d7bc45462fc8205c8";
      fetchSubmodules = false;
      sha256 = "sha256-CiRiZRmD7tuy/fNQwYJohiS1KSL+7ihTm29cMHunUWE=";
    };
    as = "evergarden";
    date = "2025-04-25";
  };
  fidget = {
    pname = "fidget";
    version = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
      fetchSubmodules = false;
      sha256 = "sha256-8Gl2Ck4YJGReSEq1Xeh1dpdRq4eImmrxvIHrfxdem3Q=";
    };
    date = "2023-11-09";
  };
  freeze = {
    pname = "freeze";
    version = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
      fetchSubmodules = false;
      sha256 = "sha256-VdFmSRBP7Up0j5+rp7ZkfTdQmduJjsl6EZ9gf27vgZg=";
    };
    date = "2025-03-25";
  };
  fzf-lua = {
    pname = "fzf-lua";
    version = "b11467c3fbfe48e4a815e4909f5c4e5b413ce6d0";
    src = fetchFromGitHub {
      owner = "ibhagwan";
      repo = "fzf-lua";
      rev = "b11467c3fbfe48e4a815e4909f5c4e5b413ce6d0";
      fetchSubmodules = false;
      sha256 = "sha256-gvFfySq/Hua2v8Hv5Lbr3ZEtbFbdW8vN8itC5sD3Tvo=";
    };
    date = "2025-04-26";
  };
  hunk-nvim = {
    pname = "hunk-nvim";
    version = "b475ba0011e4b8ef7d7ddecd9764ee1a5f41366d";
    src = fetchFromGitHub {
      owner = "julienvincent";
      repo = "hunk.nvim";
      rev = "b475ba0011e4b8ef7d7ddecd9764ee1a5f41366d";
      fetchSubmodules = false;
      sha256 = "sha256-CKQe3kv7bX21DDqSV2S093Afs8jiAzZiLHByjWFSWDQ=";
    };
    date = "2025-02-08";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "08a02e14c8c0d42fa7a92c30a98fd04d6993b35d";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "08a02e14c8c0d42fa7a92c30a98fd04d6993b35d";
      fetchSubmodules = false;
      sha256 = "sha256-6STviireN52R7engW3c0R2Po8hHSP/apqhXvectH0So=";
    };
    date = "2025-04-01";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
      fetchSubmodules = false;
      sha256 = "sha256-0q/V+b4UrDRnaC/eRWOi9HU9a61vQSAM9/C8ZQyKt+Y=";
    };
    date = "2025-03-18";
  };
  keymaps-nvim = {
    pname = "keymaps-nvim";
    version = "221a1015f5c5f2530379983e1dc200a202f487dd";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "keymaps.nvim";
      rev = "221a1015f5c5f2530379983e1dc200a202f487dd";
      fetchSubmodules = false;
      sha256 = "sha256-afMAPHITrHKxHQKd64goFUncfbKH81t6Xyh5pFCiSTg=";
    };
    date = "2025-03-17";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lspkind = {
    pname = "lspkind";
    version = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
      fetchSubmodules = false;
      sha256 = "sha256-OCvKUBGuzwy8OWOL1x3Z3fo+0+GyBMI9TX41xSveqvE=";
    };
    date = "2024-12-05";
  };
  lualine = {
    pname = "lualine";
    version = "15884cee63a8c205334ab13ab1c891cd4d27101a";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "15884cee63a8c205334ab13ab1c891cd4d27101a";
      fetchSubmodules = false;
      sha256 = "sha256-wfNEDR3uR8Y6hZhzcnuukQ2yMz7rCvuc4li/0rkPRTA=";
    };
    date = "2025-04-22";
  };
  lz-n = {
    pname = "lz-n";
    version = "a10519ab5940a5364560043df9dc3db328e27f98";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "a10519ab5940a5364560043df9dc3db328e27f98";
      fetchSubmodules = false;
      sha256 = "sha256-YYYO8ZrK45b2NTb7CFW4F1c90LSJo0dBSSvjMaKCAKM=";
    };
    start = "true";
    date = "2025-04-27";
  };
  markit-nvim = {
    pname = "markit-nvim";
    version = "9b031afab214aa6e6467f275f55640989f438925";
    src = fetchFromGitHub {
      owner = "2KAbhishek";
      repo = "markit.nvim";
      rev = "9b031afab214aa6e6467f275f55640989f438925";
      fetchSubmodules = false;
      sha256 = "sha256-LCvACs8hHxquwBcCthfrdWQAQd8jrOwhsuZAkjqCZSQ=";
    };
    date = "2025-02-23";
  };
  markview = {
    pname = "markview";
    version = "6bbbbf5790cdea622b53fe94b49b9801037e2db9";
    src = fetchFromGitHub {
      owner = "OXY2DEV";
      repo = "markview.nvim";
      rev = "6bbbbf5790cdea622b53fe94b49b9801037e2db9";
      fetchSubmodules = false;
      sha256 = "sha256-2/XB9QRHFrbzk+MlFVCfQsMv8F26MI4YN+9TkS7o2dQ=";
    };
    date = "2025-04-26";
  };
  mini-ai = {
    pname = "mini-ai";
    version = "e139eb1101beb0250fea322f8c07a42f0f175688";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.ai";
      rev = "e139eb1101beb0250fea322f8c07a42f0f175688";
      fetchSubmodules = false;
      sha256 = "sha256-rN7nchgckFy0ZUrGAnEaLzK9fAPJkyqacM2SSju3h9E=";
    };
    date = "2025-04-01";
  };
  mini-align = {
    pname = "mini-align";
    version = "2b42ac0be7d570c2208f9e334ecef13453cd222d";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.align";
      rev = "2b42ac0be7d570c2208f9e334ecef13453cd222d";
      fetchSubmodules = false;
      sha256 = "sha256-idf1EhUm60c2jPwK6hSwP1RKw06jHFDsI/ZP4tKWaIo=";
    };
    date = "2025-04-01";
  };
  mini-bracketed = {
    pname = "mini-bracketed";
    version = "cd77e1e498a561a0f11b41a650caa1ba3a6a3fcc";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.bracketed";
      rev = "cd77e1e498a561a0f11b41a650caa1ba3a6a3fcc";
      fetchSubmodules = false;
      sha256 = "sha256-SfMb4CDvEqjgVgQp1p9Pyk9hsPa4I9IJYEPPI8eOIJE=";
    };
    date = "2025-04-01";
  };
  mini-diff = {
    pname = "mini-diff";
    version = "7e268d0241255abaa07b8aa0ddff028f7315fe21";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.diff";
      rev = "7e268d0241255abaa07b8aa0ddff028f7315fe21";
      fetchSubmodules = false;
      sha256 = "sha256-2NNuRq8rI7uYpM2auHLJie3MRTydHhG9vuyW8ncpXEc=";
    };
    date = "2025-04-06";
  };
  mini-files = {
    pname = "mini-files";
    version = "432142ada983ec5863ba480f0e4891b7d64ce3f6";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.files";
      rev = "432142ada983ec5863ba480f0e4891b7d64ce3f6";
      fetchSubmodules = false;
      sha256 = "sha256-q3zSq7eIzUArbqDEM9/todZrvfUjaj2F5l2XLpHTQhA=";
    };
    date = "2025-04-01";
  };
  mini-git = {
    pname = "mini-git";
    version = "a0ddc6302f654523053c28109e8b6dbbf05c08f8";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini-git";
      rev = "a0ddc6302f654523053c28109e8b6dbbf05c08f8";
      fetchSubmodules = false;
      sha256 = "sha256-wlu1LzBwyB12inqGP+Vp2Wbf2Dyy00fVVcF5EI72wG0=";
    };
    date = "2025-04-06";
  };
  mini-icons = {
    pname = "mini-icons";
    version = "397ed3807e96b59709ef3292f0a3e253d5c1dc0a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.icons";
      rev = "397ed3807e96b59709ef3292f0a3e253d5c1dc0a";
      fetchSubmodules = false;
      sha256 = "sha256-/sdLtMOOGeVvFDBB9N4CyUHpGXtUi1ZJ9dIpvxZ9C4Q=";
    };
    date = "2025-04-01";
  };
  mini-move = {
    pname = "mini-move";
    version = "4fe4a855fee53c66b0f3255a4b54ddc2ae6b308c";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.move";
      rev = "4fe4a855fee53c66b0f3255a4b54ddc2ae6b308c";
      fetchSubmodules = false;
      sha256 = "sha256-92y5p9g03GMfyQsO0qVUp6exIXypkpq+lJSUH7pNojU=";
    };
    date = "2025-04-01";
  };
  mini-operators = {
    pname = "mini-operators";
    version = "c6d87731f1a2c849888754347ffc5a1395bf2977";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.operators";
      rev = "c6d87731f1a2c849888754347ffc5a1395bf2977";
      fetchSubmodules = false;
      sha256 = "sha256-aoQnywJK7czFRiJKgJuwqgxZYrhbhZ+DOiHGK1WHVsY=";
    };
    date = "2025-04-01";
  };
  mini-pairs = {
    pname = "mini-pairs";
    version = "69864a2efb36c030877421634487fd90db1e4298";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.pairs";
      rev = "69864a2efb36c030877421634487fd90db1e4298";
      fetchSubmodules = false;
      sha256 = "sha256-ORD4ERYhN2F/MRpDlJvuH2wq8pgMsw/NMWiNX2eUcis=";
    };
    date = "2025-04-01";
  };
  mini-splitjoin = {
    pname = "mini-splitjoin";
    version = "70240d5d3881ff1b2b1d7902450f98a6fa303800";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.splitjoin";
      rev = "70240d5d3881ff1b2b1d7902450f98a6fa303800";
      fetchSubmodules = false;
      sha256 = "sha256-Cx/yXpFnTpleLkN4PevtzYYyiyTAv2qBRQhtRjS45Oo=";
    };
    date = "2025-04-01";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "5aab42fcdcf31fa010f012771eda5631c077840a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "5aab42fcdcf31fa010f012771eda5631c077840a";
      fetchSubmodules = false;
      sha256 = "sha256-fsJf1wOLPLSjAgGcjrckwrK1qkpyPjKHMeqEj589XkM=";
    };
    date = "2025-04-01";
  };
  mini-trailspace = {
    pname = "mini-trailspace";
    version = "39a0460c025a605519fdd6bea1ce870642429996";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.trailspace";
      rev = "39a0460c025a605519fdd6bea1ce870642429996";
      fetchSubmodules = false;
      sha256 = "sha256-z3kevj896GtxGd44cIM0sU84sBkV2fQf2gq6UzvbJbU=";
    };
    date = "2025-04-01";
  };
  mossy-nvim = {
    pname = "mossy-nvim";
    version = "873837584102b12e4ea0fcb375312a86c6c42ff1";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "mossy.nvim";
      rev = "873837584102b12e4ea0fcb375312a86c6c42ff1";
      fetchSubmodules = false;
      sha256 = "sha256-9nmpoxfpzRrBkwg/3zc585sg3P0LnSsg0uXpR9wZYwY=";
    };
    date = "2025-03-17";
  };
  neogen = {
    pname = "neogen";
    version = "05d754004da8c89115b291f2a23ca530a8cac8fd";
    src = fetchFromGitHub {
      owner = "danymat";
      repo = "neogen";
      rev = "05d754004da8c89115b291f2a23ca530a8cac8fd";
      fetchSubmodules = false;
      sha256 = "sha256-ebYUXDsVRI4Gz6boSVRrWv1aQbT2fKnO21iBraBp+mQ=";
    };
    date = "2025-02-20";
  };
  nui = {
    pname = "nui";
    version = "8d5b0b568517935d3c84f257f272ef004d9f5a59";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "8d5b0b568517935d3c84f257f272ef004d9f5a59";
      fetchSubmodules = false;
      sha256 = "sha256-Ne2evWxGUjRzhCGPibmrhNBCWmzUEHxT/U14iolptXw=";
    };
    date = "2025-04-23";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "517df88cf2afb36652830df2c655df2da416a0ae";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "517df88cf2afb36652830df2c655df2da416a0ae";
      fetchSubmodules = false;
      sha256 = "sha256-yOPUgqHe0WT437aX8kp0P/reNgjZUNNRG7hvDgaeXT0=";
    };
    date = "2025-03-01";
  };
  nvim-lint = {
    pname = "nvim-lint";
    version = "9dfb77ef6c5092a19502883c02dc5a02ec648729";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-lint";
      rev = "9dfb77ef6c5092a19502883c02dc5a02ec648729";
      fetchSubmodules = false;
      sha256 = "sha256-QN2gnCx5cSpFOi8dkq9wM4iFD1iCxbvh3pnJBOhb4hw=";
    };
    date = "2025-04-23";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "94d0fec9135719e046903bbbbf8f39e3d3436d4e";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "94d0fec9135719e046903bbbbf8f39e3d3436d4e";
      fetchSubmodules = false;
      sha256 = "sha256-V8qxiPdJMCbI3wMnT9sA37w5v+1BsW2o6/c6e5u66/I=";
    };
    start = "true";
    date = "2025-04-30";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "d0a8c17c4dc721b00bc2ac305c6ffbb036beeb74";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "d0a8c17c4dc721b00bc2ac305c6ffbb036beeb74";
      fetchSubmodules = false;
      sha256 = "sha256-7L1rww1Z6NfcaOV5LUjspfwDhOk0asii8DdHmTe3ulc=";
    };
    date = "2025-04-30";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "b5825cf9ee881dd8e43309c93374ed5b87b7a896";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "b5825cf9ee881dd8e43309c93374ed5b87b7a896";
      fetchSubmodules = false;
      sha256 = "sha256-m4dQ8KuMhbEpRh6zLTlIUDN9ojFj69LZnXXLepmdFI8=";
    };
    date = "2025-04-13";
  };
  nvim-tree = {
    pname = "nvim-tree";
    version = "582ae48c9e43d2bcd55dfcc8e2e7a1f29065d924";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "582ae48c9e43d2bcd55dfcc8e2e7a1f29065d924";
      fetchSubmodules = false;
      sha256 = "sha256-RKgNmKWd6ARlmqCSjTZXhdaA9efkG/DfpndXgguh6vY=";
    };
    date = "2025-04-26";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "94ea4f436d2b59c80f02e293466c374584f03b8c";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "94ea4f436d2b59c80f02e293466c374584f03b8c";
      fetchSubmodules = false;
      sha256 = "sha256-hAjB/TBZJfeX2ViCCHzrqcJ6pVHMHOrNcBTcZpv6XdA=";
    };
    date = "2025-04-30";
  };
  plenary = {
    pname = "plenary";
    version = "857c5ac632080dba10aae49dba902ce3abf91b35";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "857c5ac632080dba10aae49dba902ce3abf91b35";
      fetchSubmodules = false;
      sha256 = "sha256-8FV5RjF7QbDmQOQynpK7uRKONKbPRYbOPugf9ZxNvUs=";
    };
    start = "true";
    date = "2025-02-11";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "08103ea02643a93065fe7dbc4ed22275719fc338";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "08103ea02643a93065fe7dbc4ed22275719fc338";
      fetchSubmodules = false;
      sha256 = "sha256-SDMoqQwY3cKj5c5wHFdE+G0ZWVIeLjF6DU67tfDfi8w=";
    };
    date = "2024-12-10";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "55ad4fb76ab68460f700599b7449385f0c4e858e";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "55ad4fb76ab68460f700599b7449385f0c4e858e";
      fetchSubmodules = false;
      sha256 = "sha256-EeJvGtBwZgR7i9PEnGe4NTRiDQCgVKkSh5t8Xy5EYfE=";
    };
    date = "2025-04-16";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "3f2b7a94b7fa3c0f301dfa9644c94b543000efc2";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "3f2b7a94b7fa3c0f301dfa9644c94b543000efc2";
      fetchSubmodules = false;
      sha256 = "sha256-xf8GEAmq4l5OhzdcveTwPhVO25gp0tfP2H7S50c1ffg=";
    };
    date = "2025-04-27";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "d521e71f9d5ac1c29a7653528d4e5c66ffe229c5";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "d521e71f9d5ac1c29a7653528d4e5c66ffe229c5";
      fetchSubmodules = false;
      sha256 = "sha256-GlxAg+HVan1kK9OHtnNVUxk57t5U1Pqn4UJ80FKa4j8=";
    };
    date = "2025-04-30";
  };
  shelf-nvim = {
    pname = "shelf-nvim";
    version = "c580fbffa2599ab6236486d35102c30598f60812";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "shelf.nvim";
      rev = "c580fbffa2599ab6236486d35102c30598f60812";
      fetchSubmodules = false;
      sha256 = "sha256-phO1/tOZ9Qq3M7no+G9PFPB+Gqf0eHSWnBw15SMEX3w=";
    };
    date = "2024-06-24";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "bc0630e43be5699bb94dadc302c0d21615421d93";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      fetchSubmodules = false;
      sha256 = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
    date = "2025-03-01";
  };
  symbol-usage = {
    pname = "symbol-usage";
    version = "e8712de8f339d40f96c0c89566f9bb97e647599d";
    src = fetchFromGitHub {
      owner = "Wansmer";
      repo = "symbol-usage.nvim";
      rev = "e8712de8f339d40f96c0c89566f9bb97e647599d";
      fetchSubmodules = false;
      sha256 = "sha256-VzliC8LARRXt/5yJN28K7UcM7sP7RQWW5CLw+a0mv0Q=";
    };
    date = "2025-04-22";
  };
  tabby-nvim = {
    pname = "tabby-nvim";
    version = "6362aa9595428cefbb6556c05390e8444d1bcd12";
    src = fetchFromGitHub {
      owner = "nanozuki";
      repo = "tabby.nvim";
      rev = "6362aa9595428cefbb6556c05390e8444d1bcd12";
      fetchSubmodules = false;
      sha256 = "sha256-5aV7SgduOca9oOl8bdtBnQMoXFXD7uPNUcqN14ZGL8s=";
    };
    date = "2025-04-04";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
      fetchSubmodules = false;
      sha256 = "sha256-at9OSBtQqyiDdxKdNn2x6z4k8xrDD90sACKEK7uKNUM=";
    };
    date = "2025-01-14";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "9a88eae817ef395952e08650b3283726786fb5fb";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "9a88eae817ef395952e08650b3283726786fb5fb";
      fetchSubmodules = false;
      sha256 = "sha256-fytbX+L12TK45YKFU9K+iFJcDrwboKabihc2LtX29J4=";
    };
    date = "2025-03-09";
  };
  treewalker = {
    pname = "treewalker";
    version = "34bf0a6044e0b5e3d93b7012ae7bdf457de91ba1";
    src = fetchFromGitHub {
      owner = "aaronik";
      repo = "treewalker.nvim";
      rev = "34bf0a6044e0b5e3d93b7012ae7bdf457de91ba1";
      fetchSubmodules = false;
      sha256 = "sha256-01fT04tM7gfuFUO3amidJNARG4N4jrip4rSTnR3XPWY=";
    };
    date = "2025-04-16";
  };
  trouble = {
    pname = "trouble";
    version = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
      fetchSubmodules = false;
      sha256 = "sha256-au9wp88a0CutEf2f8Bi0vFTUR0zvQKgFX1vMVg4myGI=";
    };
    date = "2025-02-12";
  };
  undotree = {
    pname = "undotree";
    version = "b951b87b46c34356d44aa71886aecf9dd7f5788a";
    src = fetchFromGitHub {
      owner = "mbbill";
      repo = "undotree";
      rev = "b951b87b46c34356d44aa71886aecf9dd7f5788a";
      fetchSubmodules = false;
      sha256 = "sha256-HGf4Toe+12YZtIalvANDXAtksCsnxQkZbcevOAnl5G4=";
    };
    date = "2025-03-13";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "4a745ea72fa93bb15dd077109afbb3d1809383f2";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "4a745ea72fa93bb15dd077109afbb3d1809383f2";
      fetchSubmodules = false;
      sha256 = "sha256-1AteNwnc7lCHLIwM8Ejm2T9VTIDM+CeAfvAUeSQRFKE=";
    };
    date = "2025-02-19";
  };
  wakatime = {
    pname = "wakatime";
    version = "3cb40867cb5a3120f9bef76eff88edc7f1dc1a23";
    src = fetchFromGitHub {
      owner = "wakatime";
      repo = "vim-wakatime";
      rev = "3cb40867cb5a3120f9bef76eff88edc7f1dc1a23";
      fetchSubmodules = false;
      sha256 = "sha256-HxLmX+qws8A6+mFBGMdru2E3NXJ91P0HtDKMX8ryMzI=";
    };
    date = "2024-04-29";
  };
  zk-nvim = {
    pname = "zk-nvim";
    version = "d9e7442075d2241b90fc788a149c509ebc45f3cb";
    src = fetchFromGitHub {
      owner = "mickael-menu";
      repo = "zk-nvim";
      rev = "d9e7442075d2241b90fc788a149c509ebc45f3cb";
      fetchSubmodules = false;
      sha256 = "sha256-okZfzeEmQ4KbCn7Y1J0bahaK69IBpuaOt5WtUh9/bv4=";
    };
    date = "2025-05-01";
  };
}
