# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bqf = {
    pname = "bqf";
    version = "e20417d5e589e03eaaaadc4687904528500608be";
    src = fetchFromGitHub {
      owner = "kevinhwang91";
      repo = "nvim-bqf";
      rev = "e20417d5e589e03eaaaadc4687904528500608be";
      fetchSubmodules = false;
      sha256 = "sha256-prYpUlsPIESgA3HXSk5WNFXhxAYVFZeOMQoYZxq9rj8=";
    };
    date = "2025-03-29";
  };
  bufferline = {
    pname = "bufferline";
    version = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
      fetchSubmodules = false;
      sha256 = "sha256-ae4MB6+6v3awvfSUWlau9ASJ147ZpwuX1fvJdfMwo1Q=";
    };
    date = "2025-01-14";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "5b5e3aef9ad7af84f463d17b5479f06b87d5c429";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "5b5e3aef9ad7af84f463d17b5479f06b87d5c429";
      fetchSubmodules = false;
      sha256 = "sha256-4h/fzFY8JR9r+QnoiWEqgQKPMuu8i9HTC4v0Jp7iuUo=";
    };
    as = "catppuccin";
    date = "2025-03-01";
  };
  chai-nvim = {
    pname = "chai-nvim";
    version = "5b3142493114ade681dfad63417e5989c11f0f6d";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "chai.nvim";
      rev = "5b3142493114ade681dfad63417e5989c11f0f6d";
      fetchSubmodules = false;
      sha256 = "sha256-T2KHSYdRNbqAPpZrzzRBkTmhS8YV1eiHfnRR1QG5D9k=";
    };
    start = "true";
    as = "chai";
    date = "2025-03-21";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "d1b6e6ced09fbe15b96741de5fa84e89479f3144";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "d1b6e6ced09fbe15b96741de5fa84e89479f3144";
      fetchSubmodules = false;
      sha256 = "sha256-LmYtBdRrLWYaM76Wy1jVa8pBK8XloANqfqO1zZewD8Y=";
    };
    date = "2025-04-08";
  };
  crates = {
    pname = "crates";
    version = "a63681f36d06cf733ccbd296481957fb1efa6d09";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "a63681f36d06cf733ccbd296481957fb1efa6d09";
      fetchSubmodules = false;
      sha256 = "sha256-PhtEJ8oCXYJWKbLU4RmrFbV5qlqNVgkh8rwxDoYfiQ0=";
    };
    date = "2025-04-06";
  };
  direnv = {
    pname = "direnv";
    version = "8e8c2a1d6ed8b422e231dd610785d2a585daeafa";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "8e8c2a1d6ed8b422e231dd610785d2a585daeafa";
      fetchSubmodules = false;
      sha256 = "sha256-nQNl5s/vpNWpkExK3H1ma53IR9aojRQfxZwbwqCNEh8=";
    };
    date = "2025-03-21";
  };
  evergarden = {
    pname = "evergarden";
    version = "892400e77ae2fa3b24d56bcf97347581a6fc0921";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "nvim";
      rev = "892400e77ae2fa3b24d56bcf97347581a6fc0921";
      fetchSubmodules = false;
      sha256 = "sha256-fAQ4powtr3/l410KoQ+D3FShh3R2DesO8O2VXIvVAoo=";
    };
    as = "evergarden";
    date = "2025-04-12";
  };
  fidget = {
    pname = "fidget";
    version = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
      fetchSubmodules = false;
      sha256 = "sha256-8Gl2Ck4YJGReSEq1Xeh1dpdRq4eImmrxvIHrfxdem3Q=";
    };
    date = "2023-11-09";
  };
  freeze = {
    pname = "freeze";
    version = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
      fetchSubmodules = false;
      sha256 = "sha256-VdFmSRBP7Up0j5+rp7ZkfTdQmduJjsl6EZ9gf27vgZg=";
    };
    date = "2025-03-25";
  };
  fzf-lua = {
    pname = "fzf-lua";
    version = "47b85a25c0c0b2c20b4e75199ed01bb71e7814f5";
    src = fetchFromGitHub {
      owner = "ibhagwan";
      repo = "fzf-lua";
      rev = "47b85a25c0c0b2c20b4e75199ed01bb71e7814f5";
      fetchSubmodules = false;
      sha256 = "sha256-N4SbyNyHEN4D8NxaeIiBibR4Z5iNBVvUjXR0gtaG1P4=";
    };
    date = "2025-04-08";
  };
  hunk-nvim = {
    pname = "hunk-nvim";
    version = "b475ba0011e4b8ef7d7ddecd9764ee1a5f41366d";
    src = fetchFromGitHub {
      owner = "julienvincent";
      repo = "hunk.nvim";
      rev = "b475ba0011e4b8ef7d7ddecd9764ee1a5f41366d";
      fetchSubmodules = false;
      sha256 = "sha256-CKQe3kv7bX21DDqSV2S093Afs8jiAzZiLHByjWFSWDQ=";
    };
    date = "2025-02-08";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "08a02e14c8c0d42fa7a92c30a98fd04d6993b35d";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "08a02e14c8c0d42fa7a92c30a98fd04d6993b35d";
      fetchSubmodules = false;
      sha256 = "sha256-6STviireN52R7engW3c0R2Po8hHSP/apqhXvectH0So=";
    };
    date = "2025-04-01";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
      fetchSubmodules = false;
      sha256 = "sha256-0q/V+b4UrDRnaC/eRWOi9HU9a61vQSAM9/C8ZQyKt+Y=";
    };
    date = "2025-03-18";
  };
  keymaps-nvim = {
    pname = "keymaps-nvim";
    version = "221a1015f5c5f2530379983e1dc200a202f487dd";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "keymaps.nvim";
      rev = "221a1015f5c5f2530379983e1dc200a202f487dd";
      fetchSubmodules = false;
      sha256 = "sha256-afMAPHITrHKxHQKd64goFUncfbKH81t6Xyh5pFCiSTg=";
    };
    date = "2025-03-17";
  };
  lazydev = {
    pname = "lazydev";
    version = "2367a6c0a01eb9edb0464731cc0fb61ed9ab9d2c";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "2367a6c0a01eb9edb0464731cc0fb61ed9ab9d2c";
      fetchSubmodules = false;
      sha256 = "sha256-LoxziiV9jlHuU4vRVFfKtVLI45ouJcuyXC6DIyQKlew=";
    };
    date = "2025-02-20";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lspkind = {
    pname = "lspkind";
    version = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
      fetchSubmodules = false;
      sha256 = "sha256-OCvKUBGuzwy8OWOL1x3Z3fo+0+GyBMI9TX41xSveqvE=";
    };
    date = "2024-12-05";
  };
  lualine = {
    pname = "lualine";
    version = "1ba400068bc178eb698b96ecfde82db59e7a7b8f";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "1ba400068bc178eb698b96ecfde82db59e7a7b8f";
      fetchSubmodules = false;
      sha256 = "sha256-zOO20MX6OC8sXuUuUY0ykJNMeS9W1OnoF/zHdRkxKXM=";
    };
    date = "2025-04-08";
  };
  lz-n = {
    pname = "lz-n";
    version = "2ef8dfbef6f8f97873da4c5820067343690d114c";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "2ef8dfbef6f8f97873da4c5820067343690d114c";
      fetchSubmodules = false;
      sha256 = "sha256-FmEvGwqtN9hb7S91BcFOOPecjVv4YKZFRLAqv7FXJoY=";
    };
    start = "true";
    date = "2025-04-06";
  };
  markit-nvim = {
    pname = "markit-nvim";
    version = "9b031afab214aa6e6467f275f55640989f438925";
    src = fetchFromGitHub {
      owner = "2KAbhishek";
      repo = "markit.nvim";
      rev = "9b031afab214aa6e6467f275f55640989f438925";
      fetchSubmodules = false;
      sha256 = "sha256-LCvACs8hHxquwBcCthfrdWQAQd8jrOwhsuZAkjqCZSQ=";
    };
    date = "2025-02-23";
  };
  markview = {
    pname = "markview";
    version = "4f9ad36efe01c283aa886453ba75bf569c897c84";
    src = fetchFromGitHub {
      owner = "OXY2DEV";
      repo = "markview.nvim";
      rev = "4f9ad36efe01c283aa886453ba75bf569c897c84";
      fetchSubmodules = false;
      sha256 = "sha256-nDBFVDgu2mz4YWBNYXXWpDwh0CyvPRxWVfHvX21xj8s=";
    };
    date = "2025-04-04";
  };
  mini-ai = {
    pname = "mini-ai";
    version = "e139eb1101beb0250fea322f8c07a42f0f175688";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.ai";
      rev = "e139eb1101beb0250fea322f8c07a42f0f175688";
      fetchSubmodules = false;
      sha256 = "sha256-rN7nchgckFy0ZUrGAnEaLzK9fAPJkyqacM2SSju3h9E=";
    };
    date = "2025-04-01";
  };
  mini-align = {
    pname = "mini-align";
    version = "2b42ac0be7d570c2208f9e334ecef13453cd222d";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.align";
      rev = "2b42ac0be7d570c2208f9e334ecef13453cd222d";
      fetchSubmodules = false;
      sha256 = "sha256-idf1EhUm60c2jPwK6hSwP1RKw06jHFDsI/ZP4tKWaIo=";
    };
    date = "2025-04-01";
  };
  mini-bracketed = {
    pname = "mini-bracketed";
    version = "cd77e1e498a561a0f11b41a650caa1ba3a6a3fcc";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.bracketed";
      rev = "cd77e1e498a561a0f11b41a650caa1ba3a6a3fcc";
      fetchSubmodules = false;
      sha256 = "sha256-SfMb4CDvEqjgVgQp1p9Pyk9hsPa4I9IJYEPPI8eOIJE=";
    };
    date = "2025-04-01";
  };
  mini-diff = {
    pname = "mini-diff";
    version = "7e268d0241255abaa07b8aa0ddff028f7315fe21";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.diff";
      rev = "7e268d0241255abaa07b8aa0ddff028f7315fe21";
      fetchSubmodules = false;
      sha256 = "sha256-2NNuRq8rI7uYpM2auHLJie3MRTydHhG9vuyW8ncpXEc=";
    };
    date = "2025-04-06";
  };
  mini-files = {
    pname = "mini-files";
    version = "432142ada983ec5863ba480f0e4891b7d64ce3f6";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.files";
      rev = "432142ada983ec5863ba480f0e4891b7d64ce3f6";
      fetchSubmodules = false;
      sha256 = "sha256-q3zSq7eIzUArbqDEM9/todZrvfUjaj2F5l2XLpHTQhA=";
    };
    date = "2025-04-01";
  };
  mini-git = {
    pname = "mini-git";
    version = "a0ddc6302f654523053c28109e8b6dbbf05c08f8";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini-git";
      rev = "a0ddc6302f654523053c28109e8b6dbbf05c08f8";
      fetchSubmodules = false;
      sha256 = "sha256-wlu1LzBwyB12inqGP+Vp2Wbf2Dyy00fVVcF5EI72wG0=";
    };
    date = "2025-04-06";
  };
  mini-move = {
    pname = "mini-move";
    version = "4fe4a855fee53c66b0f3255a4b54ddc2ae6b308c";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.move";
      rev = "4fe4a855fee53c66b0f3255a4b54ddc2ae6b308c";
      fetchSubmodules = false;
      sha256 = "sha256-92y5p9g03GMfyQsO0qVUp6exIXypkpq+lJSUH7pNojU=";
    };
    date = "2025-04-01";
  };
  mini-operators = {
    pname = "mini-operators";
    version = "c6d87731f1a2c849888754347ffc5a1395bf2977";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.operators";
      rev = "c6d87731f1a2c849888754347ffc5a1395bf2977";
      fetchSubmodules = false;
      sha256 = "sha256-aoQnywJK7czFRiJKgJuwqgxZYrhbhZ+DOiHGK1WHVsY=";
    };
    date = "2025-04-01";
  };
  mini-pairs = {
    pname = "mini-pairs";
    version = "69864a2efb36c030877421634487fd90db1e4298";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.pairs";
      rev = "69864a2efb36c030877421634487fd90db1e4298";
      fetchSubmodules = false;
      sha256 = "sha256-ORD4ERYhN2F/MRpDlJvuH2wq8pgMsw/NMWiNX2eUcis=";
    };
    date = "2025-04-01";
  };
  mini-splitjoin = {
    pname = "mini-splitjoin";
    version = "70240d5d3881ff1b2b1d7902450f98a6fa303800";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.splitjoin";
      rev = "70240d5d3881ff1b2b1d7902450f98a6fa303800";
      fetchSubmodules = false;
      sha256 = "sha256-Cx/yXpFnTpleLkN4PevtzYYyiyTAv2qBRQhtRjS45Oo=";
    };
    date = "2025-04-01";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "5aab42fcdcf31fa010f012771eda5631c077840a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "5aab42fcdcf31fa010f012771eda5631c077840a";
      fetchSubmodules = false;
      sha256 = "sha256-fsJf1wOLPLSjAgGcjrckwrK1qkpyPjKHMeqEj589XkM=";
    };
    date = "2025-04-01";
  };
  mini-trailspace = {
    pname = "mini-trailspace";
    version = "39a0460c025a605519fdd6bea1ce870642429996";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.trailspace";
      rev = "39a0460c025a605519fdd6bea1ce870642429996";
      fetchSubmodules = false;
      sha256 = "sha256-z3kevj896GtxGd44cIM0sU84sBkV2fQf2gq6UzvbJbU=";
    };
    date = "2025-04-01";
  };
  mossy-nvim = {
    pname = "mossy-nvim";
    version = "873837584102b12e4ea0fcb375312a86c6c42ff1";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "mossy.nvim";
      rev = "873837584102b12e4ea0fcb375312a86c6c42ff1";
      fetchSubmodules = false;
      sha256 = "sha256-9nmpoxfpzRrBkwg/3zc585sg3P0LnSsg0uXpR9wZYwY=";
    };
    date = "2025-03-17";
  };
  neogen = {
    pname = "neogen";
    version = "05d754004da8c89115b291f2a23ca530a8cac8fd";
    src = fetchFromGitHub {
      owner = "danymat";
      repo = "neogen";
      rev = "05d754004da8c89115b291f2a23ca530a8cac8fd";
      fetchSubmodules = false;
      sha256 = "sha256-ebYUXDsVRI4Gz6boSVRrWv1aQbT2fKnO21iBraBp+mQ=";
    };
    date = "2025-02-20";
  };
  none-ls = {
    pname = "none-ls";
    version = "6377e77dae38015d0a8c24852530098f1d8a24f6";
    src = fetchFromGitHub {
      owner = "nvimtools";
      repo = "none-ls.nvim";
      rev = "6377e77dae38015d0a8c24852530098f1d8a24f6";
      fetchSubmodules = false;
      sha256 = "sha256-d07Bo7hMsSjzozbg8uXyDwcVofeVi6jISSLW/Vai1dA=";
    };
    date = "2025-04-05";
  };
  nui = {
    pname = "nui";
    version = "8d3bce9764e627b62b07424e0df77f680d47ffdb";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "8d3bce9764e627b62b07424e0df77f680d47ffdb";
      fetchSubmodules = false;
      sha256 = "sha256-BYTY2ezYuxsneAl/yQbwL1aQvVWKSsN3IVqzTlrBSEU=";
    };
    date = "2025-03-06";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "517df88cf2afb36652830df2c655df2da416a0ae";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "517df88cf2afb36652830df2c655df2da416a0ae";
      fetchSubmodules = false;
      sha256 = "sha256-yOPUgqHe0WT437aX8kp0P/reNgjZUNNRG7hvDgaeXT0=";
    };
    date = "2025-03-01";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "9ae789e7450995e4c06ed9f8f74629992d5d28a6";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "9ae789e7450995e4c06ed9f8f74629992d5d28a6";
      fetchSubmodules = false;
      sha256 = "sha256-R6Jd+ObzhgQ8qBDdv0Wx2kUisoOysN+6GkmQKNWdBwY=";
    };
    date = "2025-04-08";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "8649f694d3e76ee10c19255dece6411c29206a54";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "8649f694d3e76ee10c19255dece6411c29206a54";
      fetchSubmodules = false;
      sha256 = "sha256-0p5n/V8Jlj9XyxV/fuMwsbQ7oV5m9H2GqZZEA/njxCQ=";
    };
    date = "2023-11-30";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "22f29093eae7785773ee9d543f8750348b1a195c";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "22f29093eae7785773ee9d543f8750348b1a195c";
      fetchSubmodules = false;
      sha256 = "sha256-6vNfc7E9DMXF0IBXJCLA8Rp+uOgbDch/Q7beW0ys3Vo=";
    };
    date = "2025-01-20";
  };
  nvim-tree = {
    pname = "nvim-tree";
    version = "c3c193594213c5e2f89ec5d7729cad805f76b256";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "c3c193594213c5e2f89ec5d7729cad805f76b256";
      fetchSubmodules = false;
      sha256 = "sha256-az/LmM7neWWUtoA3bfp8e7UpXS2c9BVOroifLSWtp5s=";
    };
    date = "2025-04-04";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "0e21ee8df6235511c02bab4a5b391d18e165a58d";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "0e21ee8df6235511c02bab4a5b391d18e165a58d";
      fetchSubmodules = false;
      sha256 = "sha256-gCCxRnWMSd/GZzAGpTau4nwWM/bI/lbhhvShEv5anak=";
    };
    date = "2025-04-07";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "57dfa947cc88cdf1baa2c7e13ed31edddd8fb1d1";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "57dfa947cc88cdf1baa2c7e13ed31edddd8fb1d1";
      fetchSubmodules = false;
      sha256 = "sha256-EXs2ErtvhSqHB5cXSmgj4Y3nfv6exP19xGiVqYQ+gRs=";
    };
    date = "2025-04-07";
  };
  plenary = {
    pname = "plenary";
    version = "857c5ac632080dba10aae49dba902ce3abf91b35";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "857c5ac632080dba10aae49dba902ce3abf91b35";
      fetchSubmodules = false;
      sha256 = "sha256-8FV5RjF7QbDmQOQynpK7uRKONKbPRYbOPugf9ZxNvUs=";
    };
    start = "true";
    date = "2025-02-11";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "08103ea02643a93065fe7dbc4ed22275719fc338";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "08103ea02643a93065fe7dbc4ed22275719fc338";
      fetchSubmodules = false;
      sha256 = "sha256-SDMoqQwY3cKj5c5wHFdE+G0ZWVIeLjF6DU67tfDfi8w=";
    };
    date = "2024-12-10";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "de39919a57e1a40a4c7dc5bae0de276f9c616ef3";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "de39919a57e1a40a4c7dc5bae0de276f9c616ef3";
      fetchSubmodules = false;
      sha256 = "sha256-sQAVw+9bKmJzX/MHA/vcmvzL+Q5kyWpDfPJ97efxQxE=";
    };
    date = "2025-03-24";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "3f327d15a3c1ed48b1e1087e16873a28a39768c2";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "3f327d15a3c1ed48b1e1087e16873a28a39768c2";
      fetchSubmodules = false;
      sha256 = "sha256-ci/N6hrM7L+dCNGrSsq2SPSwt/7sc3JLVz2guX51mSc=";
    };
    date = "2025-04-08";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "9961c820c0fb66288056093e8fb8056570a1eb9a";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "9961c820c0fb66288056093e8fb8056570a1eb9a";
      fetchSubmodules = false;
      sha256 = "sha256-VgmaiZ1Fe0aIAewPOUmzQqKpj21m3OS63B04LKLVQu8=";
    };
    date = "2025-04-09";
  };
  shelf-nvim = {
    pname = "shelf-nvim";
    version = "c580fbffa2599ab6236486d35102c30598f60812";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "shelf.nvim";
      rev = "c580fbffa2599ab6236486d35102c30598f60812";
      fetchSubmodules = false;
      sha256 = "sha256-phO1/tOZ9Qq3M7no+G9PFPB+Gqf0eHSWnBw15SMEX3w=";
    };
    date = "2024-06-24";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "bc0630e43be5699bb94dadc302c0d21615421d93";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      fetchSubmodules = false;
      sha256 = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
    date = "2025-03-01";
  };
  symbol-usage = {
    pname = "symbol-usage";
    version = "0f9b3da014b7e41559b643e7461fcabb2a7dc83a";
    src = fetchFromGitHub {
      owner = "Wansmer";
      repo = "symbol-usage.nvim";
      rev = "0f9b3da014b7e41559b643e7461fcabb2a7dc83a";
      fetchSubmodules = false;
      sha256 = "sha256-vNVrh8MV7KZoh2MtP+hAr6Uz20qMMMUcbua/W71lRn0=";
    };
    date = "2024-09-13";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
      fetchSubmodules = false;
      sha256 = "sha256-at9OSBtQqyiDdxKdNn2x6z4k8xrDD90sACKEK7uKNUM=";
    };
    date = "2025-01-14";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "9a88eae817ef395952e08650b3283726786fb5fb";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "9a88eae817ef395952e08650b3283726786fb5fb";
      fetchSubmodules = false;
      sha256 = "sha256-fytbX+L12TK45YKFU9K+iFJcDrwboKabihc2LtX29J4=";
    };
    date = "2025-03-09";
  };
  treewalker = {
    pname = "treewalker";
    version = "7d993149867ea05898626bf19df8b7d020de10ef";
    src = fetchFromGitHub {
      owner = "aaronik";
      repo = "treewalker.nvim";
      rev = "7d993149867ea05898626bf19df8b7d020de10ef";
      fetchSubmodules = false;
      sha256 = "sha256-duheuMWsX+kEDzYOuWHG2XvXXeLXEG2aADnCMR7aDbA=";
    };
    date = "2025-04-05";
  };
  trouble = {
    pname = "trouble";
    version = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
      fetchSubmodules = false;
      sha256 = "sha256-au9wp88a0CutEf2f8Bi0vFTUR0zvQKgFX1vMVg4myGI=";
    };
    date = "2025-02-12";
  };
  undotree = {
    pname = "undotree";
    version = "b951b87b46c34356d44aa71886aecf9dd7f5788a";
    src = fetchFromGitHub {
      owner = "mbbill";
      repo = "undotree";
      rev = "b951b87b46c34356d44aa71886aecf9dd7f5788a";
      fetchSubmodules = false;
      sha256 = "sha256-HGf4Toe+12YZtIalvANDXAtksCsnxQkZbcevOAnl5G4=";
    };
    date = "2025-03-13";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "4a745ea72fa93bb15dd077109afbb3d1809383f2";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "4a745ea72fa93bb15dd077109afbb3d1809383f2";
      fetchSubmodules = false;
      sha256 = "sha256-1AteNwnc7lCHLIwM8Ejm2T9VTIDM+CeAfvAUeSQRFKE=";
    };
    date = "2025-02-19";
  };
  wakatime = {
    pname = "wakatime";
    version = "3cb40867cb5a3120f9bef76eff88edc7f1dc1a23";
    src = fetchFromGitHub {
      owner = "wakatime";
      repo = "vim-wakatime";
      rev = "3cb40867cb5a3120f9bef76eff88edc7f1dc1a23";
      fetchSubmodules = false;
      sha256 = "sha256-HxLmX+qws8A6+mFBGMdru2E3NXJ91P0HtDKMX8ryMzI=";
    };
    date = "2024-04-29";
  };
  which-key = {
    pname = "which-key";
    version = "370ec46f710e058c9c1646273e6b225acf47cbed";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "370ec46f710e058c9c1646273e6b225acf47cbed";
      fetchSubmodules = false;
      sha256 = "sha256-uvMcSduMr7Kd2oUmIOYzvWF4FIl6bZxIYm9FSw/3pCo=";
    };
    date = "2025-02-22";
  };
  zk-nvim = {
    pname = "zk-nvim";
    version = "d0bac443233635d18968affde4701db2cf2435b5";
    src = fetchFromGitHub {
      owner = "mickael-menu";
      repo = "zk-nvim";
      rev = "d0bac443233635d18968affde4701db2cf2435b5";
      fetchSubmodules = false;
      sha256 = "sha256-zhpbtxVZhU5Vtzj4z6F3/CuSb9Q0JhlAI8yyhMgPjIo=";
    };
    date = "2025-04-05";
  };
}
