# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bqf = {
    pname = "bqf";
    version = "a77b17e39b1b707b6feee86a36c83703c1534c08";
    src = fetchFromGitHub {
      owner = "kevinhwang91";
      repo = "nvim-bqf";
      rev = "a77b17e39b1b707b6feee86a36c83703c1534c08";
      fetchSubmodules = false;
      sha256 = "sha256-uWhr7i0oFD1N2IhBhwwSy3CrX9EXG/4brlL/6VGocl0=";
    };
    date = "2025-10-06";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "e79d09fa347b367e0e7f693bfe87dba932a8cbd1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "e79d09fa347b367e0e7f693bfe87dba932a8cbd1";
      fetchSubmodules = false;
      sha256 = "sha256-WmWGygttH78KajAaIvlwRW47G7UGJuPV0YIfEZkse6I=";
    };
    as = "catppuccin";
    date = "2025-10-05";
  };
  chai-nvim = {
    pname = "chai-nvim";
    version = "5b3142493114ade681dfad63417e5989c11f0f6d";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "chai.nvim";
      rev = "5b3142493114ade681dfad63417e5989c11f0f6d";
      fetchSubmodules = false;
      sha256 = "sha256-T2KHSYdRNbqAPpZrzzRBkTmhS8YV1eiHfnRR1QG5D9k=";
    };
    as = "chai";
    start = "true";
    date = "2025-03-21";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  crates = {
    pname = "crates";
    version = "ac9fa498a9edb96dc3056724ff69d5f40b898453";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "ac9fa498a9edb96dc3056724ff69d5f40b898453";
      fetchSubmodules = false;
      sha256 = "sha256-jfmST/S9ymwgQ99PTCOlJkk5zaxE5HiDV16TmTISDII=";
    };
    date = "2025-08-23";
  };
  direnv = {
    pname = "direnv";
    version = "4dfc8758a1deab45e37b7f3661e0fd3759d85788";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "4dfc8758a1deab45e37b7f3661e0fd3759d85788";
      fetchSubmodules = false;
      sha256 = "sha256-KqO8uDbVy4sVVZ6mHikuO+SWCzWr97ZuFRC8npOPJIE=";
    };
    date = "2025-06-09";
  };
  evergarden = {
    pname = "evergarden";
    version = "951d0c459f5d7fff8e90e0c0803dad8faf5180ff";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "nvim";
      rev = "951d0c459f5d7fff8e90e0c0803dad8faf5180ff";
      fetchSubmodules = false;
      sha256 = "sha256-JwJeuTN3cDM9vjPh/In8/L6trT73cwaf8NnidvASKw0=";
    };
    as = "evergarden";
    date = "2025-09-18";
  };
  fidget = {
    pname = "fidget";
    version = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
      fetchSubmodules = false;
      sha256 = "sha256-8Gl2Ck4YJGReSEq1Xeh1dpdRq4eImmrxvIHrfxdem3Q=";
    };
    date = "2023-11-09";
  };
  freeze = {
    pname = "freeze";
    version = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
      fetchSubmodules = false;
      sha256 = "sha256-VdFmSRBP7Up0j5+rp7ZkfTdQmduJjsl6EZ9gf27vgZg=";
    };
    date = "2025-03-25";
  };
  fzf-lua = {
    pname = "fzf-lua";
    version = "c0c0926eee09f2e7868e5b72cb66decc0cb13aca";
    src = fetchFromGitHub {
      owner = "ibhagwan";
      repo = "fzf-lua";
      rev = "c0c0926eee09f2e7868e5b72cb66decc0cb13aca";
      fetchSubmodules = false;
      sha256 = "sha256-v+VdFJO5QifiA5mgyL2TV6jR/QIgJARvJPS8pE9i0aI=";
    };
    date = "2025-10-07";
  };
  keymaps-nvim = {
    pname = "keymaps-nvim";
    version = "f606f66b2aafbd0dbb4328aeab2b89e5dd9d3473";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "keymaps.nvim";
      rev = "f606f66b2aafbd0dbb4328aeab2b89e5dd9d3473";
      fetchSubmodules = false;
      sha256 = "sha256-pqbZRu9dUh/0zhC+JTYFfb5vyq+XXxygHPbfNwDeUYk=";
    };
    date = "2025-07-31";
  };
  lylla-nvim = {
    pname = "lylla-nvim";
    version = "27ab34830c7cb1f97364ee7c0fc0023906955727";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "lylla.nvim";
      rev = "27ab34830c7cb1f97364ee7c0fc0023906955727";
      fetchSubmodules = false;
      sha256 = "sha256-NxgdyxBcTKNjiO39MzyWW+shOYMp73oQHkiKYONJ47w=";
    };
    date = "2025-09-26";
  };
  lz-n = {
    pname = "lz-n";
    version = "0e8d9ba10e47a76c8649098237fec7054a1b5833";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "0e8d9ba10e47a76c8649098237fec7054a1b5833";
      fetchSubmodules = false;
      sha256 = "sha256-3tPCla/Wnw2O858ZwHaKz8ZC6IpYwjqh97XuqPASYY4=";
    };
    start = "true";
    date = "2025-10-05";
  };
  marks-nvim = {
    pname = "marks-nvim";
    version = "f353e8c08c50f39e99a9ed474172df7eddd89b72";
    src = fetchFromGitHub {
      owner = "chentoast";
      repo = "marks.nvim";
      rev = "f353e8c08c50f39e99a9ed474172df7eddd89b72";
      fetchSubmodules = false;
      sha256 = "sha256-ho2b2Ulh+GTqY0QvW7zjFOSlF5g/kaxWyOjKWhTFq7c=";
    };
    date = "2025-05-13";
  };
  mini-ai = {
    pname = "mini-ai";
    version = "11c57180bc9084089206e211ac7aa598bedc9673";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.ai";
      rev = "11c57180bc9084089206e211ac7aa598bedc9673";
      fetchSubmodules = false;
      sha256 = "sha256-4cYYb9wVo/g/z07QLnHJq02NNORat/984QXFUUuCr8g=";
    };
    date = "2025-10-03";
  };
  mini-align = {
    pname = "mini-align";
    version = "94af41078e61fbe42ec79f87e67d69c529d3c40a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.align";
      rev = "94af41078e61fbe42ec79f87e67d69c529d3c40a";
      fetchSubmodules = false;
      sha256 = "sha256-knj+Fis8JeoXze1e7s9ALwi0jYC1Bve4bK4OwqQ9bS0=";
    };
    date = "2025-10-03";
  };
  mini-bracketed = {
    pname = "mini-bracketed";
    version = "0ea3cb6478e5fdeca33b53fd08683eb2e622f6ce";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.bracketed";
      rev = "0ea3cb6478e5fdeca33b53fd08683eb2e622f6ce";
      fetchSubmodules = false;
      sha256 = "sha256-dGqV5DTrhKjQUc/2ABm5Uex/CVdIQvhgmkyHhDjhb0w=";
    };
    date = "2025-10-03";
  };
  mini-diff = {
    pname = "mini-diff";
    version = "a2df2a9a485328c20252b7cadb11feb717020e45";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.diff";
      rev = "a2df2a9a485328c20252b7cadb11feb717020e45";
      fetchSubmodules = false;
      sha256 = "sha256-F6If0wAhT26XJ10+yJNqCjiU3RkS7FYDyNsnjl4z89A=";
    };
    date = "2025-10-03";
  };
  mini-files = {
    pname = "mini-files";
    version = "51db5ded1b7ac4dd8ca4c22c66f156dac5309304";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.files";
      rev = "51db5ded1b7ac4dd8ca4c22c66f156dac5309304";
      fetchSubmodules = false;
      sha256 = "sha256-54RkSO8Fy19T2lp58xZ2iq7D3yb0DL/QwgSM2uMRqQg=";
    };
    date = "2025-10-03";
  };
  mini-git = {
    pname = "mini-git";
    version = "19600f7e3dee7e581479da4bd024551b080d90d4";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini-git";
      rev = "19600f7e3dee7e581479da4bd024551b080d90d4";
      fetchSubmodules = false;
      sha256 = "sha256-ZGI8KNY2I3SZXFhmwhrQB/ZRVvcXMr0J53mc7Ch0A50=";
    };
    date = "2025-10-03";
  };
  mini-icons = {
    pname = "mini-icons";
    version = "284798619aed9f4c1ac1b9417b9a5e3b4b85ef3a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.icons";
      rev = "284798619aed9f4c1ac1b9417b9a5e3b4b85ef3a";
      fetchSubmodules = false;
      sha256 = "sha256-kjQ8SScf/Gi4cJPfBfMCa9oi/PcuguJdIHk1jYxMBEw=";
    };
    date = "2025-10-03";
  };
  mini-jump2d = {
    pname = "mini-jump2d";
    version = "5ff749990336e67195724d1dcddfea4e50057a19";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.jump2d";
      rev = "5ff749990336e67195724d1dcddfea4e50057a19";
      fetchSubmodules = false;
      sha256 = "sha256-Bjy3rqV5rFxFk08DIFY4ECvuqRze3cK7asiqAlKFGDM=";
    };
    date = "2025-10-03";
  };
  mini-move = {
    pname = "mini-move";
    version = "f33406ae7d95b931c6a0d3ba11e50983fe800afb";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.move";
      rev = "f33406ae7d95b931c6a0d3ba11e50983fe800afb";
      fetchSubmodules = false;
      sha256 = "sha256-KODqg7QwGucuR1D+6MfQLUYkAlf6JiF8+Vz19GpZ2L8=";
    };
    date = "2025-10-03";
  };
  mini-operators = {
    pname = "mini-operators";
    version = "1d0d1e1570e5bd22e6df3bcb068d0a2ac0d30710";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.operators";
      rev = "1d0d1e1570e5bd22e6df3bcb068d0a2ac0d30710";
      fetchSubmodules = false;
      sha256 = "sha256-RwHiCb1ZaH6IyJwZWJmXF/TmFS5bWVGNXZgVt2/oi9U=";
    };
    date = "2025-10-03";
  };
  mini-pairs = {
    pname = "mini-pairs";
    version = "b9aada8c0e59f2b938e98fbf4eae0799eba96ad9";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.pairs";
      rev = "b9aada8c0e59f2b938e98fbf4eae0799eba96ad9";
      fetchSubmodules = false;
      sha256 = "sha256-KFWpyITaKc9AGhvpLkeq9B3a5MELqed2UBo9X8oC6Ac=";
    };
    date = "2025-10-03";
  };
  mini-splitjoin = {
    pname = "mini-splitjoin";
    version = "b0d57bb5d1ed154e5902ae2745f1a320a7642443";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.splitjoin";
      rev = "b0d57bb5d1ed154e5902ae2745f1a320a7642443";
      fetchSubmodules = false;
      sha256 = "sha256-7Oo4I/rr3tNyEIXOki/ZBftt8vJc7koEvQTBSWqFsKo=";
    };
    date = "2025-10-03";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "fc6fbc319b2d686c524d71c7feda20f71af15b8e";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "fc6fbc319b2d686c524d71c7feda20f71af15b8e";
      fetchSubmodules = false;
      sha256 = "sha256-ADu+BTItiRnqTgYg5Iz2BKL2zXcQC8l/eVAvI2z2oGs=";
    };
    date = "2025-10-07";
  };
  mini-trailspace = {
    pname = "mini-trailspace";
    version = "fab31f4955207cf84e28e7bed5cff35cccaf317f";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.trailspace";
      rev = "fab31f4955207cf84e28e7bed5cff35cccaf317f";
      fetchSubmodules = false;
      sha256 = "sha256-1wonX56fOcvKSSRkRDfRrjtMHjx8nCMNv+0XKMPVWT8=";
    };
    date = "2025-10-03";
  };
  mossy-nvim = {
    pname = "mossy-nvim";
    version = "c2b23ee260909e28985f2a24a4f999bb363f9696";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "mossy.nvim";
      rev = "c2b23ee260909e28985f2a24a4f999bb363f9696";
      fetchSubmodules = false;
      sha256 = "sha256-Uo2wSHIqcw6mQC5b5d0HcZ5hZ19O4voAt4v9zb4+5dk=";
    };
    date = "2025-09-16";
  };
  neo-tree = {
    pname = "neo-tree";
    version = "0c29e3795b9105d68390d2fdfd430409ef8c5d65";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "0c29e3795b9105d68390d2fdfd430409ef8c5d65";
      fetchSubmodules = false;
      sha256 = "sha256-9odPVhANPpYtZ3dXcnSZ2y2zWWaf4bnwd40ZHDJ61A0=";
    };
    date = "2025-10-07";
  };
  neogen = {
    pname = "neogen";
    version = "d7f9461727751fb07f82011051338a9aba07581d";
    src = fetchFromGitHub {
      owner = "danymat";
      repo = "neogen";
      rev = "d7f9461727751fb07f82011051338a9aba07581d";
      fetchSubmodules = false;
      sha256 = "sha256-uXV8YZLO44lFys1RfIqsvonC2YEYwb1iiaiLfsON3hE=";
    };
    date = "2025-05-03";
  };
  nivvie-nvim = {
    pname = "nivvie-nvim";
    version = "f2ee7cd6aae80f7b3a7ed9c6f7c3b21110fb5706";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "nivvie.nvim";
      rev = "f2ee7cd6aae80f7b3a7ed9c6f7c3b21110fb5706";
      fetchSubmodules = false;
      sha256 = "sha256-sUHC146fALmpBcyk6yW8uIdBXVzu5oBHuTr/sGMq3sc=";
    };
    date = "2025-08-21";
  };
  nui = {
    pname = "nui";
    version = "de740991c12411b663994b2860f1a4fd0937c130";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "de740991c12411b663994b2860f1a4fd0937c130";
      fetchSubmodules = false;
      sha256 = "sha256-41slmnvt1z7sCxvpiVuFmQ9g7eCaxQi1dDCL3AxSL1A=";
    };
    date = "2025-06-08";
  };
  nvim-lint = {
    pname = "nvim-lint";
    version = "9da1fb942dd0668d5182f9c8dee801b9c190e2bb";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-lint";
      rev = "9da1fb942dd0668d5182f9c8dee801b9c190e2bb";
      fetchSubmodules = false;
      sha256 = "sha256-wVEX0lCxeipvwCfdd2JbQwnhgg6UrTXixC8E1OiEblI=";
    };
    date = "2025-10-07";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "e688b486fe9291f151eae7e5c0b5a5c4ef980847";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "e688b486fe9291f151eae7e5c0b5a5c4ef980847";
      fetchSubmodules = false;
      sha256 = "sha256-K56vjTUkQ/NdA6vq5942zUknPiCUbMByiEW540dR8R0=";
    };
    start = "true";
    date = "2025-10-04";
  };
  nvim-nio = {
    pname = "nvim-nio";
    version = "21f5324bfac14e22ba26553caf69ec76ae8a7662";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "nvim-nio";
      rev = "21f5324bfac14e22ba26553caf69ec76ae8a7662";
      fetchSubmodules = false;
      sha256 = "sha256-eDbzJAGdUBhTwuD0Nt9FihZj1MmVdQfn/GKIybuu5a8=";
    };
    date = "2025-01-20";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "3ab4f2d2d20be55874e2eb575145c6928d7d7d0e";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "3ab4f2d2d20be55874e2eb575145c6928d7d7d0e";
      fetchSubmodules = false;
      sha256 = "sha256-1zVgNJJiKVskWF+eLllLB51iwg10Syx9IDzp90fFDWU=";
    };
    start = "true";
    date = "2025-10-07";
  };
  nvim-treesitter-context = {
    pname = "nvim-treesitter-context";
    version = "41847d3dafb5004464708a3db06b14f12bde548a";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-context";
      rev = "41847d3dafb5004464708a3db06b14f12bde548a";
      fetchSubmodules = false;
      sha256 = "sha256-+yj8bstmffVByX3Z/1vkUYdXvpmWGbPt+RDfkBnV11w=";
    };
    date = "2025-09-10";
  };
  plenary = {
    pname = "plenary";
    version = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
      fetchSubmodules = false;
      sha256 = "sha256-9Un7ekhBxcnmFE1xjCCFTZ7eqIbmXvQexpnhduAg4M0=";
    };
    start = "true";
    date = "2025-07-26";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "c3e40509b6f4a428091fb1e42c3e992ba0e09fb0";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "c3e40509b6f4a428091fb1e42c3e992ba0e09fb0";
      fetchSubmodules = false;
      sha256 = "sha256-Q5/2V+KvZSJ375/4lGC5x3CwcS0oSs1gB59PRTCXkn4=";
    };
    date = "2025-08-05";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "3277ad5f96eb03c9d618c88e24f683e4364e578c";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "3277ad5f96eb03c9d618c88e24f683e4364e578c";
      fetchSubmodules = false;
      sha256 = "sha256-E0ZPi9Vzc3TwhNHsGyABY+sgn/vO6Oyun6eRd7/RFgU=";
    };
    date = "2025-09-29";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "f3d6d9afc8f09bf4dec91bf2bb5a40fcfe7ea477";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "f3d6d9afc8f09bf4dec91bf2bb5a40fcfe7ea477";
      fetchSubmodules = false;
      sha256 = "sha256-ekvoerVARxSXdMz3wPy5mwNANOM+rJbpYWbkmnREX/M=";
    };
    date = "2025-10-07";
  };
  shelf-nvim = {
    pname = "shelf-nvim";
    version = "686c8d2cce891ab5ffd881b88f549592a8ef40a9";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "shelf.nvim";
      rev = "686c8d2cce891ab5ffd881b88f549592a8ef40a9";
      fetchSubmodules = false;
      sha256 = "sha256-qnzVu0VwenQWGfJBhFcjWyT5B/U3vsLq+2O4VxAeA0M=";
    };
    date = "2025-08-07";
  };
  symbol-usage = {
    pname = "symbol-usage";
    version = "e07c07dfe7504295a369281e95a24e1afa14b243";
    src = fetchFromGitHub {
      owner = "Wansmer";
      repo = "symbol-usage.nvim";
      rev = "e07c07dfe7504295a369281e95a24e1afa14b243";
      fetchSubmodules = false;
      sha256 = "sha256-zWT6ZGYGpWLwuUrMlmyTIE5UZtPLX2FnywhycTxUaRQ=";
    };
    date = "2025-05-03";
  };
  tabby-nvim = {
    pname = "tabby-nvim";
    version = "b3affa6db7eab80fca2a2db5b73b473144507039";
    src = fetchFromGitHub {
      owner = "nanozuki";
      repo = "tabby.nvim";
      rev = "b3affa6db7eab80fca2a2db5b73b473144507039";
      fetchSubmodules = false;
      sha256 = "sha256-26ysSn0klZYMPEaxCe/1zD2qCYwobU5dZSq5P/GtwMU=";
    };
    date = "2025-05-23";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "9a88eae817ef395952e08650b3283726786fb5fb";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "9a88eae817ef395952e08650b3283726786fb5fb";
      fetchSubmodules = false;
      sha256 = "sha256-fytbX+L12TK45YKFU9K+iFJcDrwboKabihc2LtX29J4=";
    };
    date = "2025-03-09";
  };
  treewalker = {
    pname = "treewalker";
    version = "2f6fc4957bf428764863aa35f57549e9246a3943";
    src = fetchFromGitHub {
      owner = "aaronik";
      repo = "treewalker.nvim";
      rev = "2f6fc4957bf428764863aa35f57549e9246a3943";
      fetchSubmodules = false;
      sha256 = "sha256-MymyvrCzrtzPfPHGAniwFf8VG12AQXdGJ5gq9CHX17Q=";
    };
    date = "2025-10-02";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4";
      fetchSubmodules = false;
      sha256 = "sha256-u39oObHCXk8uew5HyVdV1Z69Viilv3B7x1SUJxYXYLo=";
    };
    date = "2025-07-15";
  };
  vim-startuptime = {
    pname = "vim-startuptime";
    version = "b6f0d93f6b8cf6eee0b4c94450198ba2d6a05ff6";
    src = fetchFromGitHub {
      owner = "dstein64";
      repo = "vim-startuptime";
      rev = "b6f0d93f6b8cf6eee0b4c94450198ba2d6a05ff6";
      fetchSubmodules = false;
      sha256 = "sha256-0YLDkU1y89O5z7tgxaH5USQpJDfTuN0fsPJOAp6pa5Y=";
    };
    date = "2025-02-17";
  };
  yosu-nvim = {
    pname = "yosu-nvim";
    version = "b92a8d9e294025f1d249a24f0b2538c9a8a14007";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "yosu.nvim";
      rev = "b92a8d9e294025f1d249a24f0b2538c9a8a14007";
      fetchSubmodules = false;
      sha256 = "sha256-ao7fnihe/aKyL3XAgqgIj5aVUhVS20JsYV56+QfNoJ4=";
    };
    date = "2025-05-09";
  };
  zk-nvim = {
    pname = "zk-nvim";
    version = "8e0446f448e03dfe76ab671724f4c8db7a46cd37";
    src = fetchFromGitHub {
      owner = "mickael-menu";
      repo = "zk-nvim";
      rev = "8e0446f448e03dfe76ab671724f4c8db7a46cd37";
      fetchSubmodules = false;
      sha256 = "sha256-2kA6Iomkx0/b5xwhOqFqP6NLb3D419dq0ox7AD3kkLc=";
    };
    date = "2025-09-15";
  };
}
