# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bqf = {
    pname = "bqf";
    version = "dd17c73912487dccb372deff85d4262d2b89bc2b";
    src = fetchFromGitHub {
      owner = "kevinhwang91";
      repo = "nvim-bqf";
      rev = "dd17c73912487dccb372deff85d4262d2b89bc2b";
      fetchSubmodules = false;
      sha256 = "sha256-WJrTOqqO4w9YRErTr6rGb8RxJA+HxKaZGlV2mGl64GM=";
    };
    date = "2025-07-20";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "94f6e8a06b6bb7b8e5529cf9f93adb4654534241";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "94f6e8a06b6bb7b8e5529cf9f93adb4654534241";
      fetchSubmodules = false;
      sha256 = "sha256-lnIlYUhUQXuoVWv000n5Ev4YNSZY+U70b3npZbMUDg4=";
    };
    as = "catppuccin";
    date = "2025-07-29";
  };
  chai-nvim = {
    pname = "chai-nvim";
    version = "5b3142493114ade681dfad63417e5989c11f0f6d";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "chai.nvim";
      rev = "5b3142493114ade681dfad63417e5989c11f0f6d";
      fetchSubmodules = false;
      sha256 = "sha256-T2KHSYdRNbqAPpZrzzRBkTmhS8YV1eiHfnRR1QG5D9k=";
    };
    as = "chai";
    start = "true";
    date = "2025-03-21";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  crates = {
    pname = "crates";
    version = "c915ab5334a46178f64ce17ab606a79454bcd14f";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "c915ab5334a46178f64ce17ab606a79454bcd14f";
      fetchSubmodules = false;
      sha256 = "sha256-5Vu3VG6Ab1Rpqzeqoa0S9sfzco7wykrSt2eSXOajm14=";
    };
    date = "2025-07-22";
  };
  direnv = {
    pname = "direnv";
    version = "4dfc8758a1deab45e37b7f3661e0fd3759d85788";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "4dfc8758a1deab45e37b7f3661e0fd3759d85788";
      fetchSubmodules = false;
      sha256 = "sha256-KqO8uDbVy4sVVZ6mHikuO+SWCzWr97ZuFRC8npOPJIE=";
    };
    date = "2025-06-09";
  };
  evergarden = {
    pname = "evergarden";
    version = "2bbb39161a770c758104af27fcf3634395b6f9ce";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "nvim";
      rev = "2bbb39161a770c758104af27fcf3634395b6f9ce";
      fetchSubmodules = false;
      sha256 = "sha256-CGXIhDb4fInFh4wcJRdYDGWpzK09C+RJ3QjEA3dv1yw=";
    };
    as = "evergarden";
    date = "2025-07-23";
  };
  fidget = {
    pname = "fidget";
    version = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
      fetchSubmodules = false;
      sha256 = "sha256-8Gl2Ck4YJGReSEq1Xeh1dpdRq4eImmrxvIHrfxdem3Q=";
    };
    date = "2023-11-09";
  };
  freeze = {
    pname = "freeze";
    version = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
      fetchSubmodules = false;
      sha256 = "sha256-VdFmSRBP7Up0j5+rp7ZkfTdQmduJjsl6EZ9gf27vgZg=";
    };
    date = "2025-03-25";
  };
  fzf-lua = {
    pname = "fzf-lua";
    version = "c6efab0fd1d8548a760e837629b84e400ac76c79";
    src = fetchFromGitHub {
      owner = "ibhagwan";
      repo = "fzf-lua";
      rev = "c6efab0fd1d8548a760e837629b84e400ac76c79";
      fetchSubmodules = false;
      sha256 = "sha256-cfmepkDkpF04UBYRw1652mMHMDbugMb+7VAFxGsDqZc=";
    };
    date = "2025-07-29";
  };
  hunk-nvim = {
    pname = "hunk-nvim";
    version = "1e0a4d719c780bb8b0690a54915601508ced321e";
    src = fetchFromGitHub {
      owner = "julienvincent";
      repo = "hunk.nvim";
      rev = "1e0a4d719c780bb8b0690a54915601508ced321e";
      fetchSubmodules = false;
      sha256 = "sha256-va7cCBuBk3WLAZjKl+lxlKmVckaK010RAdWMzrXlzAw=";
    };
    date = "2025-06-09";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "d8b6b030672f9f551a0e3526347699985a779d93";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "d8b6b030672f9f551a0e3526347699985a779d93";
      fetchSubmodules = false;
      sha256 = "sha256-6hpSJbrJEnw5NaVkGrXxXeqkObNTUPCtKJd+iZBFUM0=";
    };
    date = "2025-06-08";
  };
  keymaps-nvim = {
    pname = "keymaps-nvim";
    version = "221a1015f5c5f2530379983e1dc200a202f487dd";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "keymaps.nvim";
      rev = "221a1015f5c5f2530379983e1dc200a202f487dd";
      fetchSubmodules = false;
      sha256 = "sha256-afMAPHITrHKxHQKd64goFUncfbKH81t6Xyh5pFCiSTg=";
    };
    date = "2025-03-17";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lualine = {
    pname = "lualine";
    version = "a94fc68960665e54408fe37dcf573193c4ce82c9";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "a94fc68960665e54408fe37dcf573193c4ce82c9";
      fetchSubmodules = false;
      sha256 = "sha256-2aPgA7riA/FubQpTkqsxLKl7OZ8L6FkucNHc2QEx2HQ=";
    };
    date = "2025-06-08";
  };
  lz-n = {
    pname = "lz-n";
    version = "dbf512563eef47b04c24684a6d934a429a7706fc";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "dbf512563eef47b04c24684a6d934a429a7706fc";
      fetchSubmodules = false;
      sha256 = "sha256-2zuhF3+4fdFut7DBcf7oR19wtsahhSln33BB7iUjKF8=";
    };
    start = "true";
    date = "2025-07-27";
  };
  markit-nvim = {
    pname = "markit-nvim";
    version = "6dc7f4c4f09f40fdf8d01f81a99518db2a4efa2d";
    src = fetchFromGitHub {
      owner = "2KAbhishek";
      repo = "markit.nvim";
      rev = "6dc7f4c4f09f40fdf8d01f81a99518db2a4efa2d";
      fetchSubmodules = false;
      sha256 = "sha256-u0EDzOsxArKBi+drg2bhCQJNc0riRfkLVPgwmTZ0750=";
    };
    date = "2025-07-21";
  };
  mini-ai = {
    pname = "mini-ai";
    version = "1cd4f021a05c29acd4ab511c0981da14217daf38";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.ai";
      rev = "1cd4f021a05c29acd4ab511c0981da14217daf38";
      fetchSubmodules = false;
      sha256 = "sha256-m8uwB+SUMJylnx6pcnu+0oPsNKihWgUhjcGNhSwRrhA=";
    };
    date = "2025-07-22";
  };
  mini-align = {
    pname = "mini-align";
    version = "0202e1662a7a03a95cefd6851795ceae5e87b9b3";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.align";
      rev = "0202e1662a7a03a95cefd6851795ceae5e87b9b3";
      fetchSubmodules = false;
      sha256 = "sha256-xdEh6mh4VQky3b0RziMR6DEjbTdLvLDQQGMTX7rP/Hs=";
    };
    date = "2025-07-22";
  };
  mini-bracketed = {
    pname = "mini-bracketed";
    version = "4a005a6e5aad58230b69f0f59df2cbb8b1c2e643";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.bracketed";
      rev = "4a005a6e5aad58230b69f0f59df2cbb8b1c2e643";
      fetchSubmodules = false;
      sha256 = "sha256-fd110tEpwATu0mKSMlDcnNdHShMCOD1uIYwYYDAj4nE=";
    };
    date = "2025-07-22";
  };
  mini-diff = {
    pname = "mini-diff";
    version = "f573bd2ae2eb225ea2f125126b8869e04bcaf231";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.diff";
      rev = "f573bd2ae2eb225ea2f125126b8869e04bcaf231";
      fetchSubmodules = false;
      sha256 = "sha256-F4GEO052skNlt5vaFr/AH4QHw28T9rAIEbynzaeBimY=";
    };
    date = "2025-07-22";
  };
  mini-files = {
    pname = "mini-files";
    version = "5b9431cf5c69b8e69e5a67d2d12338a3ac2e1541";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.files";
      rev = "5b9431cf5c69b8e69e5a67d2d12338a3ac2e1541";
      fetchSubmodules = false;
      sha256 = "sha256-TA/lf25tto5/w8H/envfOkXuHSNdZj/wCftSeMLkYvg=";
    };
    date = "2025-07-22";
  };
  mini-git = {
    pname = "mini-git";
    version = "c38380e1a6582b1aee7de26e9738b1ce17366d7d";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini-git";
      rev = "c38380e1a6582b1aee7de26e9738b1ce17366d7d";
      fetchSubmodules = false;
      sha256 = "sha256-iNW20Fo3k9Dld9Stk0gOvoUDGTawZPj07kgfrFmKboc=";
    };
    date = "2025-07-22";
  };
  mini-icons = {
    pname = "mini-icons";
    version = "b8f6fa6f5a3fd0c56936252edcd691184e5aac0c";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.icons";
      rev = "b8f6fa6f5a3fd0c56936252edcd691184e5aac0c";
      fetchSubmodules = false;
      sha256 = "sha256-NTmY4He0rC+/wrPJ+9FoDoPFKT/TtmqG5IQhpmNd9B8=";
    };
    date = "2025-07-24";
  };
  mini-move = {
    pname = "mini-move";
    version = "819e90c3e113a3c826c3003ec07073f1e0677ea0";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.move";
      rev = "819e90c3e113a3c826c3003ec07073f1e0677ea0";
      fetchSubmodules = false;
      sha256 = "sha256-yoRat9jaTgTos7t0UHDQLyGoH64Ijwn7LsCYGkenbrU=";
    };
    date = "2025-07-22";
  };
  mini-operators = {
    pname = "mini-operators";
    version = "fd655907ed56434c83a6efb654b266d9c090ca82";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.operators";
      rev = "fd655907ed56434c83a6efb654b266d9c090ca82";
      fetchSubmodules = false;
      sha256 = "sha256-TGp8QDPDpCH+fBzghFDo9neMB83o/t3gyDm/V4dofrg=";
    };
    date = "2025-07-22";
  };
  mini-pairs = {
    pname = "mini-pairs";
    version = "1e1ca3f60f58d4050bf814902b472eec9963a5dd";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.pairs";
      rev = "1e1ca3f60f58d4050bf814902b472eec9963a5dd";
      fetchSubmodules = false;
      sha256 = "sha256-BcKyjylmbmUt6xF0hX7bNQWa56x+TWbHjVOvmzz3m/8=";
    };
    date = "2025-07-22";
  };
  mini-splitjoin = {
    pname = "mini-splitjoin";
    version = "51909e9883ab206f5a92deb9ca685317387586a4";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.splitjoin";
      rev = "51909e9883ab206f5a92deb9ca685317387586a4";
      fetchSubmodules = false;
      sha256 = "sha256-GUDaXslLbBdxLfIwKEwDI7LSf0GB9Etm3v0347bwN+c=";
    };
    date = "2025-07-22";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "b12fcfefd6b9b7c9e9a773bc0e3e07ae20c03351";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "b12fcfefd6b9b7c9e9a773bc0e3e07ae20c03351";
      fetchSubmodules = false;
      sha256 = "sha256-jmxdD9rrVocOczkOkyRICfD/B6SiD1glsxnIALFR/ww=";
    };
    date = "2025-07-22";
  };
  mini-trailspace = {
    pname = "mini-trailspace";
    version = "3d570d015d63ad6d3f8a90f12c6b544c2400cea9";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.trailspace";
      rev = "3d570d015d63ad6d3f8a90f12c6b544c2400cea9";
      fetchSubmodules = false;
      sha256 = "sha256-xEnpOx8erDuHUC34d6trDCFukr4oRqUbybBPTqjNefc=";
    };
    date = "2025-07-22";
  };
  mossy-nvim = {
    pname = "mossy-nvim";
    version = "1bbe62b732ef9dde75225e1ae4676142dbea2286";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "mossy.nvim";
      rev = "1bbe62b732ef9dde75225e1ae4676142dbea2286";
      fetchSubmodules = false;
      sha256 = "sha256-vzGyD1R92vasgzyDGfkaAgrd3rMmxUpVbamhxoGaCBY=";
    };
    date = "2025-06-08";
  };
  neo-tree = {
    pname = "neo-tree";
    version = "46fa0c22ca39e05fe15744102d21feb07fe9a94a";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "46fa0c22ca39e05fe15744102d21feb07fe9a94a";
      fetchSubmodules = false;
      sha256 = "sha256-RdrGoXN/R2ZrCsblEkOLpYsVd6SvBTzLxNg/hkmnx/E=";
    };
    date = "2025-07-29";
  };
  neogen = {
    pname = "neogen";
    version = "d7f9461727751fb07f82011051338a9aba07581d";
    src = fetchFromGitHub {
      owner = "danymat";
      repo = "neogen";
      rev = "d7f9461727751fb07f82011051338a9aba07581d";
      fetchSubmodules = false;
      sha256 = "sha256-uXV8YZLO44lFys1RfIqsvonC2YEYwb1iiaiLfsON3hE=";
    };
    date = "2025-05-03";
  };
  nui = {
    pname = "nui";
    version = "de740991c12411b663994b2860f1a4fd0937c130";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "de740991c12411b663994b2860f1a4fd0937c130";
      fetchSubmodules = false;
      sha256 = "sha256-41slmnvt1z7sCxvpiVuFmQ9g7eCaxQi1dDCL3AxSL1A=";
    };
    date = "2025-06-08";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "16597180b4dd81fa3d23d88c4d2f1b49154f9479";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "16597180b4dd81fa3d23d88c4d2f1b49154f9479";
      fetchSubmodules = false;
      sha256 = "sha256-xj+FwjgeQ83VT/D8EeQn1ieA+fWS5910mRskTvI5mDo=";
    };
    date = "2025-07-22";
  };
  nvim-lint = {
    pname = "nvim-lint";
    version = "9c6207559297b24f0b7c32829f8e45f7d65b991f";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-lint";
      rev = "9c6207559297b24f0b7c32829f8e45f7d65b991f";
      fetchSubmodules = false;
      sha256 = "sha256-ly5S0KAZN8Jeag22SCX+5XKqn3d+zCRN/8Jf5HlEn9I=";
    };
    date = "2025-07-20";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "3db16ceeea947517f0dc1404c24dcb5ab0c91d26";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "3db16ceeea947517f0dc1404c24dcb5ab0c91d26";
      fetchSubmodules = false;
      sha256 = "sha256-IsdjkpE+T5irvmH5fam5EmsCpzwxSEiXV3r2iXsOVT0=";
    };
    start = "true";
    date = "2025-07-29";
  };
  nvim-nio = {
    pname = "nvim-nio";
    version = "21f5324bfac14e22ba26553caf69ec76ae8a7662";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "nvim-nio";
      rev = "21f5324bfac14e22ba26553caf69ec76ae8a7662";
      fetchSubmodules = false;
      sha256 = "sha256-eDbzJAGdUBhTwuD0Nt9FihZj1MmVdQfn/GKIybuu5a8=";
    };
    date = "2025-01-20";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "b26b4258294c742c2613a7d98fe53014d1c8fe49";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "b26b4258294c742c2613a7d98fe53014d1c8fe49";
      fetchSubmodules = false;
      sha256 = "sha256-l5FP91FjwBiqmO/xjqHdjsxEawBeWHqj5W0j2g/ZPwU=";
    };
    start = "true";
    date = "2025-07-26";
  };
  plenary = {
    pname = "plenary";
    version = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
      fetchSubmodules = false;
      sha256 = "sha256-9Un7ekhBxcnmFE1xjCCFTZ7eqIbmXvQexpnhduAg4M0=";
    };
    start = "true";
    date = "2025-07-26";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "08103ea02643a93065fe7dbc4ed22275719fc338";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "08103ea02643a93065fe7dbc4ed22275719fc338";
      fetchSubmodules = false;
      sha256 = "sha256-SDMoqQwY3cKj5c5wHFdE+G0ZWVIeLjF6DU67tfDfi8w=";
    };
    date = "2024-12-10";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "97bf4b8ef9298644a29fcd9dd41a0210cf08cac7";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "97bf4b8ef9298644a29fcd9dd41a0210cf08cac7";
      fetchSubmodules = false;
      sha256 = "sha256-YzYhk9xksnZ6IMiKsE6ee6b3tUkZG6FAgLDErn9lvxA=";
    };
    date = "2025-07-24";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "f845bb055397019c4bc70f9c76376ca490f4c783";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "f845bb055397019c4bc70f9c76376ca490f4c783";
      fetchSubmodules = false;
      sha256 = "sha256-Iw3W0Inn0CpZTXyxk54WRtsXP5DYm+7bKH/HSO/diBo=";
    };
    date = "2025-07-27";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "3cd1c7267282b4d89618674de36a6d866981347e";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "3cd1c7267282b4d89618674de36a6d866981347e";
      fetchSubmodules = false;
      sha256 = "sha256-7VZmb4JPlLF4tmEuuM69etdyCIxdH1PNZlT1mijzo7o=";
    };
    date = "2025-07-29";
  };
  shelf-nvim = {
    pname = "shelf-nvim";
    version = "821ef0da188bc0e910d699416a2677699d7edcb6";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "shelf.nvim";
      rev = "821ef0da188bc0e910d699416a2677699d7edcb6";
      fetchSubmodules = false;
      sha256 = "sha256-xbSGt7MziT/01ivdsYB3EV1dbsxKDCRaHagBEXpaeo4=";
    };
    date = "2025-08-01";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "bc0630e43be5699bb94dadc302c0d21615421d93";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      fetchSubmodules = false;
      sha256 = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
    date = "2025-03-01";
  };
  symbol-usage = {
    pname = "symbol-usage";
    version = "e07c07dfe7504295a369281e95a24e1afa14b243";
    src = fetchFromGitHub {
      owner = "Wansmer";
      repo = "symbol-usage.nvim";
      rev = "e07c07dfe7504295a369281e95a24e1afa14b243";
      fetchSubmodules = false;
      sha256 = "sha256-zWT6ZGYGpWLwuUrMlmyTIE5UZtPLX2FnywhycTxUaRQ=";
    };
    date = "2025-05-03";
  };
  tabby-nvim = {
    pname = "tabby-nvim";
    version = "b3affa6db7eab80fca2a2db5b73b473144507039";
    src = fetchFromGitHub {
      owner = "nanozuki";
      repo = "tabby.nvim";
      rev = "b3affa6db7eab80fca2a2db5b73b473144507039";
      fetchSubmodules = false;
      sha256 = "sha256-26ysSn0klZYMPEaxCe/1zD2qCYwobU5dZSq5P/GtwMU=";
    };
    date = "2025-05-23";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
      fetchSubmodules = false;
      sha256 = "sha256-at9OSBtQqyiDdxKdNn2x6z4k8xrDD90sACKEK7uKNUM=";
    };
    date = "2025-01-14";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "9a88eae817ef395952e08650b3283726786fb5fb";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "9a88eae817ef395952e08650b3283726786fb5fb";
      fetchSubmodules = false;
      sha256 = "sha256-fytbX+L12TK45YKFU9K+iFJcDrwboKabihc2LtX29J4=";
    };
    date = "2025-03-09";
  };
  treewalker = {
    pname = "treewalker";
    version = "ae229700e1cce34198280f588568dc49c52d9eb1";
    src = fetchFromGitHub {
      owner = "aaronik";
      repo = "treewalker.nvim";
      rev = "ae229700e1cce34198280f588568dc49c52d9eb1";
      fetchSubmodules = false;
      sha256 = "sha256-sBkn56nIlVzxb4UC7/VpQPzYHHc2EdB+lgcIw3YfOQQ=";
    };
    date = "2025-07-16";
  };
  trouble = {
    pname = "trouble";
    version = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
      fetchSubmodules = false;
      sha256 = "sha256-au9wp88a0CutEf2f8Bi0vFTUR0zvQKgFX1vMVg4myGI=";
    };
    date = "2025-02-12";
  };
  undotree = {
    pname = "undotree";
    version = "28f2f54a34baff90ea6f4a735ef1813ad875c743";
    src = fetchFromGitHub {
      owner = "mbbill";
      repo = "undotree";
      rev = "28f2f54a34baff90ea6f4a735ef1813ad875c743";
      fetchSubmodules = false;
      sha256 = "sha256-5WofUOTYE+Nmx3A5OoZBneJBHZ8bdGEYDZ6vTMx1OE0=";
    };
    date = "2025-07-13";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4";
      fetchSubmodules = false;
      sha256 = "sha256-u39oObHCXk8uew5HyVdV1Z69Viilv3B7x1SUJxYXYLo=";
    };
    date = "2025-07-15";
  };
  vim-startuptime = {
    pname = "vim-startuptime";
    version = "b6f0d93f6b8cf6eee0b4c94450198ba2d6a05ff6";
    src = fetchFromGitHub {
      owner = "dstein64";
      repo = "vim-startuptime";
      rev = "b6f0d93f6b8cf6eee0b4c94450198ba2d6a05ff6";
      fetchSubmodules = false;
      sha256 = "sha256-0YLDkU1y89O5z7tgxaH5USQpJDfTuN0fsPJOAp6pa5Y=";
    };
    date = "2025-02-17";
  };
  yosu-nvim = {
    pname = "yosu-nvim";
    version = "b92a8d9e294025f1d249a24f0b2538c9a8a14007";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "yosu.nvim";
      rev = "b92a8d9e294025f1d249a24f0b2538c9a8a14007";
      fetchSubmodules = false;
      sha256 = "sha256-ao7fnihe/aKyL3XAgqgIj5aVUhVS20JsYV56+QfNoJ4=";
    };
    date = "2025-05-09";
  };
  zk-nvim = {
    pname = "zk-nvim";
    version = "b18782530b23ad118d578c0fa0e4d0b8d386db4c";
    src = fetchFromGitHub {
      owner = "mickael-menu";
      repo = "zk-nvim";
      rev = "b18782530b23ad118d578c0fa0e4d0b8d386db4c";
      fetchSubmodules = false;
      sha256 = "sha256-g+DK9BTIGZxujrt0QEkcp0NGt8pPrYf4XGIX+IiA1PI=";
    };
    date = "2025-06-06";
  };
}
