# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bqf = {
    pname = "bqf";
    version = "17680cda3538913e88dd4c6456c837db9ace40ae";
    src = fetchFromGitHub {
      owner = "kevinhwang91";
      repo = "nvim-bqf";
      rev = "17680cda3538913e88dd4c6456c837db9ace40ae";
      fetchSubmodules = false;
      sha256 = "sha256-ls7hlXRSO+Dhd8l+qRAMUF/MkuMuiYXkV6hyCyAKxcc=";
    };
    date = "2025-08-03";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "30fa4d122d9b22ad8b2e0ab1b533c8c26c4dde86";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "30fa4d122d9b22ad8b2e0ab1b533c8c26c4dde86";
      fetchSubmodules = false;
      sha256 = "sha256-o8VLMPriOh4+Ay5Ff0cWQYXjmihdr3x9131bKHHTsQE=";
    };
    as = "catppuccin";
    date = "2025-08-19";
  };
  chai-nvim = {
    pname = "chai-nvim";
    version = "5b3142493114ade681dfad63417e5989c11f0f6d";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "chai.nvim";
      rev = "5b3142493114ade681dfad63417e5989c11f0f6d";
      fetchSubmodules = false;
      sha256 = "sha256-T2KHSYdRNbqAPpZrzzRBkTmhS8YV1eiHfnRR1QG5D9k=";
    };
    as = "chai";
    start = "true";
    date = "2025-03-21";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  crates = {
    pname = "crates";
    version = "ac9fa498a9edb96dc3056724ff69d5f40b898453";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "ac9fa498a9edb96dc3056724ff69d5f40b898453";
      fetchSubmodules = false;
      sha256 = "sha256-jfmST/S9ymwgQ99PTCOlJkk5zaxE5HiDV16TmTISDII=";
    };
    date = "2025-08-23";
  };
  direnv = {
    pname = "direnv";
    version = "4dfc8758a1deab45e37b7f3661e0fd3759d85788";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "4dfc8758a1deab45e37b7f3661e0fd3759d85788";
      fetchSubmodules = false;
      sha256 = "sha256-KqO8uDbVy4sVVZ6mHikuO+SWCzWr97ZuFRC8npOPJIE=";
    };
    date = "2025-06-09";
  };
  evergarden = {
    pname = "evergarden";
    version = "4041ce92cf1387f19a8006c1e36969bfb5371c50";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "nvim";
      rev = "4041ce92cf1387f19a8006c1e36969bfb5371c50";
      fetchSubmodules = false;
      sha256 = "sha256-cPdpPSZCfJLJi0ZJEYV/HZlDK1Fjiktnqr3ELimrC+4=";
    };
    as = "evergarden";
    date = "2025-08-11";
  };
  fidget = {
    pname = "fidget";
    version = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
      fetchSubmodules = false;
      sha256 = "sha256-8Gl2Ck4YJGReSEq1Xeh1dpdRq4eImmrxvIHrfxdem3Q=";
    };
    date = "2023-11-09";
  };
  freeze = {
    pname = "freeze";
    version = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
      fetchSubmodules = false;
      sha256 = "sha256-VdFmSRBP7Up0j5+rp7ZkfTdQmduJjsl6EZ9gf27vgZg=";
    };
    date = "2025-03-25";
  };
  fzf-lua = {
    pname = "fzf-lua";
    version = "9482523478aa4f41322e55c6e589731b5d4a177a";
    src = fetchFromGitHub {
      owner = "ibhagwan";
      repo = "fzf-lua";
      rev = "9482523478aa4f41322e55c6e589731b5d4a177a";
      fetchSubmodules = false;
      sha256 = "sha256-vjJ4UbkT0dKhMPAazqqStUi1pAOTUWoy29rkCCfUBrs=";
    };
    date = "2025-08-26";
  };
  hunk-nvim = {
    pname = "hunk-nvim";
    version = "1e0a4d719c780bb8b0690a54915601508ced321e";
    src = fetchFromGitHub {
      owner = "julienvincent";
      repo = "hunk.nvim";
      rev = "1e0a4d719c780bb8b0690a54915601508ced321e";
      fetchSubmodules = false;
      sha256 = "sha256-va7cCBuBk3WLAZjKl+lxlKmVckaK010RAdWMzrXlzAw=";
    };
    date = "2025-06-09";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "d8b6b030672f9f551a0e3526347699985a779d93";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "d8b6b030672f9f551a0e3526347699985a779d93";
      fetchSubmodules = false;
      sha256 = "sha256-6hpSJbrJEnw5NaVkGrXxXeqkObNTUPCtKJd+iZBFUM0=";
    };
    date = "2025-06-08";
  };
  keymaps-nvim = {
    pname = "keymaps-nvim";
    version = "f606f66b2aafbd0dbb4328aeab2b89e5dd9d3473";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "keymaps.nvim";
      rev = "f606f66b2aafbd0dbb4328aeab2b89e5dd9d3473";
      fetchSubmodules = false;
      sha256 = "sha256-pqbZRu9dUh/0zhC+JTYFfb5vyq+XXxygHPbfNwDeUYk=";
    };
    date = "2025-07-31";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lz-n = {
    pname = "lz-n";
    version = "d31d6287533b93cdf2fce4e5eb49479771af4532";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "d31d6287533b93cdf2fce4e5eb49479771af4532";
      fetchSubmodules = false;
      sha256 = "sha256-g0j4BocKyGuZqxRfBNLTNs577ZC6iddT53uCPbjd+Qc=";
    };
    start = "true";
    date = "2025-08-23";
  };
  markit-nvim = {
    pname = "markit-nvim";
    version = "6dc7f4c4f09f40fdf8d01f81a99518db2a4efa2d";
    src = fetchFromGitHub {
      owner = "2KAbhishek";
      repo = "markit.nvim";
      rev = "6dc7f4c4f09f40fdf8d01f81a99518db2a4efa2d";
      fetchSubmodules = false;
      sha256 = "sha256-u0EDzOsxArKBi+drg2bhCQJNc0riRfkLVPgwmTZ0750=";
    };
    date = "2025-07-21";
  };
  mini-ai = {
    pname = "mini-ai";
    version = "50994f55b6de0c2781e217c2d5e4a613312e460e";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.ai";
      rev = "50994f55b6de0c2781e217c2d5e4a613312e460e";
      fetchSubmodules = false;
      sha256 = "sha256-NXNin/XTqK9NqhI3MLg6EWtLF5Uhfany/98uyBhwbQc=";
    };
    date = "2025-08-25";
  };
  mini-align = {
    pname = "mini-align";
    version = "0202e1662a7a03a95cefd6851795ceae5e87b9b3";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.align";
      rev = "0202e1662a7a03a95cefd6851795ceae5e87b9b3";
      fetchSubmodules = false;
      sha256 = "sha256-xdEh6mh4VQky3b0RziMR6DEjbTdLvLDQQGMTX7rP/Hs=";
    };
    date = "2025-07-22";
  };
  mini-bracketed = {
    pname = "mini-bracketed";
    version = "4a005a6e5aad58230b69f0f59df2cbb8b1c2e643";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.bracketed";
      rev = "4a005a6e5aad58230b69f0f59df2cbb8b1c2e643";
      fetchSubmodules = false;
      sha256 = "sha256-fd110tEpwATu0mKSMlDcnNdHShMCOD1uIYwYYDAj4nE=";
    };
    date = "2025-07-22";
  };
  mini-diff = {
    pname = "mini-diff";
    version = "f573bd2ae2eb225ea2f125126b8869e04bcaf231";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.diff";
      rev = "f573bd2ae2eb225ea2f125126b8869e04bcaf231";
      fetchSubmodules = false;
      sha256 = "sha256-F4GEO052skNlt5vaFr/AH4QHw28T9rAIEbynzaeBimY=";
    };
    date = "2025-07-22";
  };
  mini-files = {
    pname = "mini-files";
    version = "5b9431cf5c69b8e69e5a67d2d12338a3ac2e1541";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.files";
      rev = "5b9431cf5c69b8e69e5a67d2d12338a3ac2e1541";
      fetchSubmodules = false;
      sha256 = "sha256-TA/lf25tto5/w8H/envfOkXuHSNdZj/wCftSeMLkYvg=";
    };
    date = "2025-07-22";
  };
  mini-git = {
    pname = "mini-git";
    version = "689bb78921e34d621df8dc1733337b2c3c39a786";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini-git";
      rev = "689bb78921e34d621df8dc1733337b2c3c39a786";
      fetchSubmodules = false;
      sha256 = "sha256-Pybp02Z6gVMn3/MtM6dRHxUZ+6tiSU/M/Lp6Fp3SJkQ=";
    };
    date = "2025-08-12";
  };
  mini-icons = {
    pname = "mini-icons";
    version = "b8f6fa6f5a3fd0c56936252edcd691184e5aac0c";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.icons";
      rev = "b8f6fa6f5a3fd0c56936252edcd691184e5aac0c";
      fetchSubmodules = false;
      sha256 = "sha256-NTmY4He0rC+/wrPJ+9FoDoPFKT/TtmqG5IQhpmNd9B8=";
    };
    date = "2025-07-24";
  };
  mini-jump2d = {
    pname = "mini-jump2d";
    version = "3710fcdfbbff539e245e16ff14f2d95ffc2fb631";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.jump2d";
      rev = "3710fcdfbbff539e245e16ff14f2d95ffc2fb631";
      fetchSubmodules = false;
      sha256 = "sha256-4W5mvy61KVe/T+fkkQynOMVxh/TIdjGa9Rr+UiOGrUs=";
    };
    date = "2025-08-28";
  };
  mini-move = {
    pname = "mini-move";
    version = "819e90c3e113a3c826c3003ec07073f1e0677ea0";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.move";
      rev = "819e90c3e113a3c826c3003ec07073f1e0677ea0";
      fetchSubmodules = false;
      sha256 = "sha256-yoRat9jaTgTos7t0UHDQLyGoH64Ijwn7LsCYGkenbrU=";
    };
    date = "2025-07-22";
  };
  mini-operators = {
    pname = "mini-operators";
    version = "e72b5afec4c339aebd601a56e9ae3ef13d2f5d1a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.operators";
      rev = "e72b5afec4c339aebd601a56e9ae3ef13d2f5d1a";
      fetchSubmodules = false;
      sha256 = "sha256-yff+ahcwu4UnrZmVR/H2Jz7nO1wsze4OMK0DuQe88cQ=";
    };
    date = "2025-08-12";
  };
  mini-pairs = {
    pname = "mini-pairs";
    version = "1e1ca3f60f58d4050bf814902b472eec9963a5dd";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.pairs";
      rev = "1e1ca3f60f58d4050bf814902b472eec9963a5dd";
      fetchSubmodules = false;
      sha256 = "sha256-BcKyjylmbmUt6xF0hX7bNQWa56x+TWbHjVOvmzz3m/8=";
    };
    date = "2025-07-22";
  };
  mini-splitjoin = {
    pname = "mini-splitjoin";
    version = "51909e9883ab206f5a92deb9ca685317387586a4";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.splitjoin";
      rev = "51909e9883ab206f5a92deb9ca685317387586a4";
      fetchSubmodules = false;
      sha256 = "sha256-GUDaXslLbBdxLfIwKEwDI7LSf0GB9Etm3v0347bwN+c=";
    };
    date = "2025-07-22";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "7a8606333affe7ce637a0ba91bbafc46fc42bfa0";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "7a8606333affe7ce637a0ba91bbafc46fc42bfa0";
      fetchSubmodules = false;
      sha256 = "sha256-rBr0oQScsEOkYy/iK3YMpwsa4ediCOFfdpsKPIEW2X4=";
    };
    date = "2025-08-12";
  };
  mini-trailspace = {
    pname = "mini-trailspace";
    version = "3d570d015d63ad6d3f8a90f12c6b544c2400cea9";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.trailspace";
      rev = "3d570d015d63ad6d3f8a90f12c6b544c2400cea9";
      fetchSubmodules = false;
      sha256 = "sha256-xEnpOx8erDuHUC34d6trDCFukr4oRqUbybBPTqjNefc=";
    };
    date = "2025-07-22";
  };
  mossy-nvim = {
    pname = "mossy-nvim";
    version = "9b8a8e04c0dea5bb909490ecabc0a0649e711d8b";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "mossy.nvim";
      rev = "9b8a8e04c0dea5bb909490ecabc0a0649e711d8b";
      fetchSubmodules = false;
      sha256 = "sha256-Au2a/hSqw5TrRXfLA25QNz7tacnl9+kk04PZnPRk+HY=";
    };
    date = "2025-08-30";
  };
  neo-tree = {
    pname = "neo-tree";
    version = "bbeda076c8a2e7d16614287cd70239f577e5bf55";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "bbeda076c8a2e7d16614287cd70239f577e5bf55";
      fetchSubmodules = false;
      sha256 = "sha256-F1xXhHQiX6WvdrhwLmCRrVSqZCWkn4nyQ9WON/F5BZw=";
    };
    date = "2025-08-17";
  };
  neogen = {
    pname = "neogen";
    version = "d7f9461727751fb07f82011051338a9aba07581d";
    src = fetchFromGitHub {
      owner = "danymat";
      repo = "neogen";
      rev = "d7f9461727751fb07f82011051338a9aba07581d";
      fetchSubmodules = false;
      sha256 = "sha256-uXV8YZLO44lFys1RfIqsvonC2YEYwb1iiaiLfsON3hE=";
    };
    date = "2025-05-03";
  };
  nivvie-nvim = {
    pname = "nivvie-nvim";
    version = "f2ee7cd6aae80f7b3a7ed9c6f7c3b21110fb5706";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "nivvie.nvim";
      rev = "f2ee7cd6aae80f7b3a7ed9c6f7c3b21110fb5706";
      fetchSubmodules = false;
      sha256 = "sha256-sUHC146fALmpBcyk6yW8uIdBXVzu5oBHuTr/sGMq3sc=";
    };
    date = "2025-08-21";
  };
  nui = {
    pname = "nui";
    version = "de740991c12411b663994b2860f1a4fd0937c130";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "de740991c12411b663994b2860f1a4fd0937c130";
      fetchSubmodules = false;
      sha256 = "sha256-41slmnvt1z7sCxvpiVuFmQ9g7eCaxQi1dDCL3AxSL1A=";
    };
    date = "2025-06-08";
  };
  nvim-lint = {
    pname = "nvim-lint";
    version = "ee04d481d4e6089892c2fb2ad8924b1a053591e1";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-lint";
      rev = "ee04d481d4e6089892c2fb2ad8924b1a053591e1";
      fetchSubmodules = false;
      sha256 = "sha256-hHMKuEY4HU8IE/1VP6dUY7jmYY2YPi4+vfjJ8NW5eAw=";
    };
    date = "2025-08-21";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "3d97ec4174bcc750d70718ddedabf150536a5891";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "3d97ec4174bcc750d70718ddedabf150536a5891";
      fetchSubmodules = false;
      sha256 = "sha256-VINGbbjND5QPXlCNFnN7xxaErDx+wx1bYqR1Zf3XmCk=";
    };
    start = "true";
    date = "2025-08-26";
  };
  nvim-nio = {
    pname = "nvim-nio";
    version = "21f5324bfac14e22ba26553caf69ec76ae8a7662";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "nvim-nio";
      rev = "21f5324bfac14e22ba26553caf69ec76ae8a7662";
      fetchSubmodules = false;
      sha256 = "sha256-eDbzJAGdUBhTwuD0Nt9FihZj1MmVdQfn/GKIybuu5a8=";
    };
    date = "2025-01-20";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "85ec015f3be42a3c2c04648ff99d617d9609e5f0";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "85ec015f3be42a3c2c04648ff99d617d9609e5f0";
      fetchSubmodules = false;
      sha256 = "sha256-Nk9TYtYKIC3VA/jY4Xyhr7WFKxSU+lVRC1soNtr92DM=";
    };
    start = "true";
    date = "2025-08-26";
  };
  plenary = {
    pname = "plenary";
    version = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
      fetchSubmodules = false;
      sha256 = "sha256-9Un7ekhBxcnmFE1xjCCFTZ7eqIbmXvQexpnhduAg4M0=";
    };
    start = "true";
    date = "2025-07-26";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "c3e40509b6f4a428091fb1e42c3e992ba0e09fb0";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "c3e40509b6f4a428091fb1e42c3e992ba0e09fb0";
      fetchSubmodules = false;
      sha256 = "sha256-Q5/2V+KvZSJ375/4lGC5x3CwcS0oSs1gB59PRTCXkn4=";
    };
    date = "2025-08-05";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "97bf4b8ef9298644a29fcd9dd41a0210cf08cac7";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "97bf4b8ef9298644a29fcd9dd41a0210cf08cac7";
      fetchSubmodules = false;
      sha256 = "sha256-YzYhk9xksnZ6IMiKsE6ee6b3tUkZG6FAgLDErn9lvxA=";
    };
    date = "2025-07-24";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "1ebe3749958f4130ae5a5e55aee891cdb90bdc82";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "1ebe3749958f4130ae5a5e55aee891cdb90bdc82";
      fetchSubmodules = false;
      sha256 = "sha256-U0BwT6Vw7v0oO1xFN6R5lM/Fgc+Yr2ymWsZtRgjeorc=";
    };
    date = "2025-08-24";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "8e74c08998fd786239caba373344f4e4601e21fe";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "8e74c08998fd786239caba373344f4e4601e21fe";
      fetchSubmodules = false;
      sha256 = "sha256-+9bQVdyPmU0CvjHpT1RtbRtell3plq3mQqfAlH7/7FE=";
    };
    date = "2025-08-25";
  };
  shelf-nvim = {
    pname = "shelf-nvim";
    version = "686c8d2cce891ab5ffd881b88f549592a8ef40a9";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "shelf.nvim";
      rev = "686c8d2cce891ab5ffd881b88f549592a8ef40a9";
      fetchSubmodules = false;
      sha256 = "sha256-qnzVu0VwenQWGfJBhFcjWyT5B/U3vsLq+2O4VxAeA0M=";
    };
    date = "2025-08-07";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "bc0630e43be5699bb94dadc302c0d21615421d93";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      fetchSubmodules = false;
      sha256 = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
    date = "2025-03-01";
  };
  symbol-usage = {
    pname = "symbol-usage";
    version = "e07c07dfe7504295a369281e95a24e1afa14b243";
    src = fetchFromGitHub {
      owner = "Wansmer";
      repo = "symbol-usage.nvim";
      rev = "e07c07dfe7504295a369281e95a24e1afa14b243";
      fetchSubmodules = false;
      sha256 = "sha256-zWT6ZGYGpWLwuUrMlmyTIE5UZtPLX2FnywhycTxUaRQ=";
    };
    date = "2025-05-03";
  };
  tabby-nvim = {
    pname = "tabby-nvim";
    version = "b3affa6db7eab80fca2a2db5b73b473144507039";
    src = fetchFromGitHub {
      owner = "nanozuki";
      repo = "tabby.nvim";
      rev = "b3affa6db7eab80fca2a2db5b73b473144507039";
      fetchSubmodules = false;
      sha256 = "sha256-26ysSn0klZYMPEaxCe/1zD2qCYwobU5dZSq5P/GtwMU=";
    };
    date = "2025-05-23";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
      fetchSubmodules = false;
      sha256 = "sha256-at9OSBtQqyiDdxKdNn2x6z4k8xrDD90sACKEK7uKNUM=";
    };
    date = "2025-01-14";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "9a88eae817ef395952e08650b3283726786fb5fb";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "9a88eae817ef395952e08650b3283726786fb5fb";
      fetchSubmodules = false;
      sha256 = "sha256-fytbX+L12TK45YKFU9K+iFJcDrwboKabihc2LtX29J4=";
    };
    date = "2025-03-09";
  };
  treewalker = {
    pname = "treewalker";
    version = "357f8e11bd4a6e0a7bb3a4e49bfe9e1ed91e55f8";
    src = fetchFromGitHub {
      owner = "aaronik";
      repo = "treewalker.nvim";
      rev = "357f8e11bd4a6e0a7bb3a4e49bfe9e1ed91e55f8";
      fetchSubmodules = false;
      sha256 = "sha256-hwFA9A0vlnA7KL9JpTxSxOtozF8WlwPHd2uqH5vZ/E8=";
    };
    date = "2025-07-30";
  };
  trouble = {
    pname = "trouble";
    version = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
      fetchSubmodules = false;
      sha256 = "sha256-au9wp88a0CutEf2f8Bi0vFTUR0zvQKgFX1vMVg4myGI=";
    };
    date = "2025-02-12";
  };
  undotree = {
    pname = "undotree";
    version = "28f2f54a34baff90ea6f4a735ef1813ad875c743";
    src = fetchFromGitHub {
      owner = "mbbill";
      repo = "undotree";
      rev = "28f2f54a34baff90ea6f4a735ef1813ad875c743";
      fetchSubmodules = false;
      sha256 = "sha256-5WofUOTYE+Nmx3A5OoZBneJBHZ8bdGEYDZ6vTMx1OE0=";
    };
    date = "2025-07-13";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4";
      fetchSubmodules = false;
      sha256 = "sha256-u39oObHCXk8uew5HyVdV1Z69Viilv3B7x1SUJxYXYLo=";
    };
    date = "2025-07-15";
  };
  vim-startuptime = {
    pname = "vim-startuptime";
    version = "b6f0d93f6b8cf6eee0b4c94450198ba2d6a05ff6";
    src = fetchFromGitHub {
      owner = "dstein64";
      repo = "vim-startuptime";
      rev = "b6f0d93f6b8cf6eee0b4c94450198ba2d6a05ff6";
      fetchSubmodules = false;
      sha256 = "sha256-0YLDkU1y89O5z7tgxaH5USQpJDfTuN0fsPJOAp6pa5Y=";
    };
    date = "2025-02-17";
  };
  yosu-nvim = {
    pname = "yosu-nvim";
    version = "b92a8d9e294025f1d249a24f0b2538c9a8a14007";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "yosu.nvim";
      rev = "b92a8d9e294025f1d249a24f0b2538c9a8a14007";
      fetchSubmodules = false;
      sha256 = "sha256-ao7fnihe/aKyL3XAgqgIj5aVUhVS20JsYV56+QfNoJ4=";
    };
    date = "2025-05-09";
  };
  zk-nvim = {
    pname = "zk-nvim";
    version = "b18782530b23ad118d578c0fa0e4d0b8d386db4c";
    src = fetchFromGitHub {
      owner = "mickael-menu";
      repo = "zk-nvim";
      rev = "b18782530b23ad118d578c0fa0e4d0b8d386db4c";
      fetchSubmodules = false;
      sha256 = "sha256-g+DK9BTIGZxujrt0QEkcp0NGt8pPrYf4XGIX+IiA1PI=";
    };
    date = "2025-06-06";
  };
}
