[bqf]
fetch.github = "kevinhwang91/nvim-bqf"
src.git = "https://github.com/kevinhwang91/nvim-bqf"

[catppuccin]
fetch.github = "catppuccin/nvim"
src.git = "https://github.com/catppuccin/nvim"
passthru.as = "catppuccin"

[chai-nvim]
fetch.github = "comfysage/chai.nvim"
src.git = "https://github.com/comfysage/chai.nvim"
passthru.as = "chai"
passthru.start = "true"

[cloak]
fetch.github = "laytan/cloak.nvim"
src.git = "https://github.com/laytan/cloak.nvim"

[copilot-lua]
fetch.github = "zbirenbaum/copilot.lua"
src.git = "https://github.com/zbirenbaum/copilot.lua"

[crates]
fetch.github = "saecki/crates.nvim"
src.git = "https://github.com/saecki/crates.nvim"

[direnv]
fetch.github = "NotAShelf/direnv.nvim"
src.git = "https://github.com/NotAShelf/direnv.nvim"

[evergarden]
fetch.github = "everviolet/nvim"
src.git = "https://github.com/everviolet/nvim"
passthru.as = "evergarden"

[fidget]
fetch.github = "j-hui/fidget.nvim"
src.git = "https://github.com/j-hui/fidget.nvim"
src.branch = "legacy"

[freeze]
fetch.github = "charm-community/freeze.nvim"
src.git = "https://github.com/charm-community/freeze.nvim"

[fzf-lua]
fetch.github = "ibhagwan/fzf-lua"
src.git = "https://github.com/ibhagwan/fzf-lua"

[hunk-nvim]
fetch.github = "julienvincent/hunk.nvim"
src.git = "https://github.com/julienvincent/hunk.nvim"

[img-clip-nvim]
fetch.github = "HakonHarnes/img-clip.nvim"
src.git = "https://github.com/HakonHarnes/img-clip.nvim"

[indent-blankline]
fetch.github = "lukas-reineke/indent-blankline.nvim"
src.git = "https://github.com/lukas-reineke/indent-blankline.nvim"

[keymaps-nvim]
fetch.github = "comfysage/keymaps.nvim"
src.git = "https://github.com/comfysage/keymaps.nvim"

[lazydev]
fetch.github = "folke/lazydev.nvim"
src.git = "https://github.com/folke/lazydev.nvim"

[lsp-status]
fetch.github = "nvim-lua/lsp-status.nvim"
src.git = "https://github.com/nvim-lua/lsp-status.nvim"

[lspkind]
fetch.github = "onsails/lspkind.nvim"
src.git = "https://github.com/onsails/lspkind.nvim"

[lualine]
fetch.github = "nvim-lualine/lualine.nvim"
src.git = "https://github.com/nvim-lualine/lualine.nvim"

[lz-n]
fetch.github = "nvim-neorocks/lz.n"
src.git = "https://github.com/nvim-neorocks/lz.n"
passthru.start = "true"

[markit-nvim]
fetch.github = "2KAbhishek/markit.nvim"
src.git = "https://github.com/2KAbhishek/markit.nvim"

[markview]
fetch.github = "OXY2DEV/markview.nvim"
src.git = "https://github.com/OXY2DEV/markview.nvim"

[mini-ai]
fetch.github = "echasnovski/mini.ai"
src.git = "https://github.com/echasnovski/mini.ai"

[mini-align]
fetch.github = "echasnovski/mini.align"
src.git = "https://github.com/echasnovski/mini.align"

[mini-bracketed]
fetch.github = "echasnovski/mini.bracketed"
src.git = "https://github.com/echasnovski/mini.bracketed"

[mini-diff]
fetch.github = "echasnovski/mini.diff"
src.git = "https://github.com/echasnovski/mini.diff"

[mini-files]
fetch.github = "echasnovski/mini.files"
src.git = "https://github.com/echasnovski/mini.files"

[mini-git]
fetch.github = "echasnovski/mini-git"
src.git = "https://github.com/echasnovski/mini-git"

[mini-icons]
fetch.github = "echasnovski/mini.icons"
src.git = "https://github.com/echasnovski/mini.icons"

[mini-move]
fetch.github = "echasnovski/mini.move"
src.git = "https://github.com/echasnovski/mini.move"

[mini-operators]
fetch.github = "echasnovski/mini.operators"
src.git = "https://github.com/echasnovski/mini.operators"

[mini-pairs]
fetch.github = "echasnovski/mini.pairs"
src.git = "https://github.com/echasnovski/mini.pairs"

[mini-splitjoin]
fetch.github = "echasnovski/mini.splitjoin"
src.git = "https://github.com/echasnovski/mini.splitjoin"

[mini-surround]
fetch.github = "echasnovski/mini.surround"
src.git = "https://github.com/echasnovski/mini.surround"

[mini-trailspace]
fetch.github = "echasnovski/mini.trailspace"
src.git = "https://github.com/echasnovski/mini.trailspace"

[neogen]
fetch.github = "danymat/neogen"
src.git = "https://github.com/danymat/neogen"

[none-ls]
fetch.github = "nvimtools/none-ls.nvim"
src.git = "https://github.com/nvimtools/none-ls.nvim"

[nui]
fetch.github = "MunifTanjim/nui.nvim"
src.git = "https://github.com/MunifTanjim/nui.nvim"

[nvim-colorizer]
fetch.github = "nvchad/nvim-colorizer.lua"
src.git = "https://github.com/nvchad/nvim-colorizer.lua"

[nvim-lspconfig]
fetch.github = "neovim/nvim-lspconfig"
src.git = "https://github.com/neovim/nvim-lspconfig"
passthru.start = "true"

[nvim-navic]
fetch.github = "SmiteshP/nvim-navic"
src.git = "https://github.com/SmiteshP/nvim-navic"

[nvim-notify]
fetch.github = "rcarriga/nvim-notify"
src.git = "https://github.com/rcarriga/nvim-notify"

[nvim-tree]
fetch.github = "nvim-tree/nvim-tree.lua"
src.git = "https://github.com/nvim-tree/nvim-tree.lua"

[nvim-treesitter]
fetch.github = "nvim-treesitter/nvim-treesitter"
src.git = "https://github.com/nvim-treesitter/nvim-treesitter"

[plenary]
fetch.github = "nvim-lua/plenary.nvim"
src.git = "https://github.com/nvim-lua/plenary.nvim"
passthru.start = "true"

[quill-nvim]
fetch.github = "comfysage/quill.nvim"
src.git = "https://github.com/comfysage/quill.nvim"

[rainbow-delimiters]
fetch.github = "hiphish/rainbow-delimiters.nvim"
src.git = "https://github.com/hiphish/rainbow-delimiters.nvim"

[rustaceanvim]
fetch.github = "mrcjkb/rustaceanvim"
src.git = "https://github.com/mrcjkb/rustaceanvim"

[sayama-nvim]
fetch.github = "comfysage/sayama.nvim"
src.git = "https://github.com/comfysage/sayama.nvim"

[schemastore]
fetch.github = "b0o/schemastore.nvim"
src.git = "https://github.com/b0o/schemastore.nvim"

[shelf-nvim]
fetch.github = "comfysage/shelf.nvim"
src.git = "https://github.com/comfysage/shelf.nvim"

[snacks-nvim]
fetch.github = "folke/snacks.nvim"
src.git = "https://github.com/folke/snacks.nvim"

[symbol-usage]
fetch.github = "Wansmer/symbol-usage.nvim"
src.git = "https://github.com/Wansmer/symbol-usage.nvim"

[mossy-nvim]
fetch.github = "comfysage/mossy.nvim"
src.git = "https://github.com/comfysage/mossy.nvim"

[tabby-nvim]
fetch.github = "nanozuki/tabby.nvim"
src.git = "https://github.com/nanozuki/tabby.nvim"

[todo-comments]
fetch.github = "folke/todo-comments.nvim"
src.git = "https://github.com/folke/todo-comments.nvim"

[toggleterm]
fetch.github = "akinsho/toggleterm.nvim"
src.git = "https://github.com/akinsho/toggleterm.nvim"

[treewalker]
fetch.github = "aaronik/treewalker.nvim"
src.git = "https://github.com/aaronik/treewalker.nvim"

[trouble]
fetch.github = "folke/trouble.nvim"
src.git = "https://github.com/folke/trouble.nvim"

[undotree]
fetch.github = "mbbill/undotree"
src.git = "https://github.com/mbbill/undotree"

[vim-fugitive]
fetch.github = "tpope/vim-fugitive"
src.git = "https://github.com/tpope/vim-fugitive"

[wakatime]
pinned = true
fetch.github = "wakatime/vim-wakatime"
src.git = "https://github.com/wakatime/vim-wakatime"

[which-key]
fetch.github = "folke/which-key.nvim"
src.git = "https://github.com/folke/which-key.nvim"

[zk-nvim]
fetch.github = "mickael-menu/zk-nvim"
src.git = "https://github.com/mickael-menu/zk-nvim"
